### ISSUE TITLE
Proposal: Sort linkages also by increasing number number of corrections

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1045]
Problem example:
``` text
linkparser> He made a request that there be an investigation
Found 52 linkages (22 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 1.05 LEN=21)

                 +-----------------MVp----------------+
                 +-------------MVp------------+       |
                 +---------Osn--------+       |       |
    +---->WV---->+----Os----+         |       |       +------Js-----+
    +->Wd--+--Ss-+    +Dsu*c+         |       |       |    +--Ds**v-+
    |      |     |    |     |         |       |       |    |        |
LEFT-WALL he made.v-d a request.n that.j-p there.r be.#by an investigation.s

Press RETURN for the next linkage.
linkparser> 
	Linkage 2, cost vector = (UNUSED=0 DIS= 1.15 LEN=13)

    +---->WV---->+----Os----+         +------Ixj-----+-----Ost----+
    +->Wd--+--Ss-+    +Dsu*c+----TS---+-SFIst>+      |   +--Ds**v-+
    |      |     |    |     |         |       |      |   |        |
LEFT-WALL he made.v-d a request.n that.j-c there.r be.v an investigation.s
```

**Comment by linas** [comment]
Oof. I would rather just increase the cost, for now. The better solution is to adjust costs according to dialect: the cost should be high for normal English, low for patois or Irish or Southern or wherever this kind of "misspelling" is common. It's kind of worse than that: its really what various authors and literary artists tried to write down to capture "authentic" accents. And there's not much written in that style, and that style has gone out of fashion a bit, its only in older novels.

I'm going to push a fix for this in just a moment.

**Comment by linas** [comment]
We could turn sorting criteria into a vector, so that the sort order is governed by the dot product
(unused, cost, length, spell-cor) times a weight vector, e.g. (1.0, 0.2, 0.05, 0.2)  and sort according to that ...  but I don't have any good theoretical intuition for what the weights should be, or what kind of theory we should apply. (In psycho-linguistics, ideas like "hubbiness" have been explored, as well as weighted distance measures.) But without a good theory, it feels like shooting in the dark.
