### ISSUE TITLE
www.abisource.com certificate is expired

### ISSUE THREAD

**Issue by vsbogd** [opencog/link-grammar#1097]
```
$ wget http://www.abisource.com/downloads/link-grammar/current
--2020-06-02 22:03:39--  http://www.abisource.com/downloads/link-grammar/current
Resolving www.abisource.com (www.abisource.com)... 130.89.149.216
Connecting to www.abisource.com (www.abisource.com)|130.89.149.216|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.abisource.com/downloads/link-grammar/current [following]
--2020-06-02 22:03:40--  https://www.abisource.com/downloads/link-grammar/current
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Connecting to www.abisource.com (www.abisource.com)|130.89.149.216|:443... connected.
ERROR: The certificate of ‘www.abisource.com’ is not trusted.
ERROR: The certificate of ‘www.abisource.com’ has expired.
The certificate has expired
```

**Comment by ngeiswei** [comment]
Alternatively it looks like we could just bypass abisource by downloading directly from

https://github.com/opencog/link-grammar/releases

**Comment by ngeiswei** [comment]
@vsbogd, I'm thinking of perhaps submitting a PR to fix it (downloading from github instead of abisource), however I don't know where that wget call takes place, searching github reveals multiple places

https://github.com/search?q=org%3Aopencog+wget+http%3A%2F%2Fwww.abisource.com%2Fdownloads%2Flink-grammar%2Fcurrent&type=Code

Any idea which is the one?

**Comment by vsbogd** [comment]
@ngeiswei , I have tried it yesterday, unfortunately it is not enough to download because Github releases doesn't have `configure` script built. My last attempt is here: https://github.com/vsbogd/ocpkg/commit/8259211cdd3cbf965b1b6ea8d92f08451df7d377

**Comment by vsbogd** [comment]
Ok, finally I made it https://github.com/vsbogd/ocpkg/commit/60f66e2dd1e7acc245ccdec39b10895cc49e52ee, but now `relex` image building procedure fails.

**Comment by linas** [comment]
The github releases https://github.com/opencog/link-grammar/releases are fundamentally broken. I would like to disable them because they suck, but there is no way to turn off this "feature" aka bug that I can find.

Anyway, the abisource certificates have been renewed. They are using the "Let's Encrypt" certificate authority, and there have been some hiccups/burps with that system, as they change their API's. (or rather, I assume that is the explanation)

**Comment by linas** [comment]
To be clear, the problem with the github releases is that ... they do not contain `configure` ... and it is easy to build broken `configure`s by installing the wrong tools, or failing to install the complete collection of tools. 

If you want to go down that path, you need to run `./autogen.sh` but, beffore doing that, make sure you have the autotools-extra (autotools-archive) package installed.

**Comment by linas** [comment]
Closing, cause I think the certificate issue has been resolved.
