### ISSUE TITLE
#  define link_public_api(x) __attribute__((visibility("default")))

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1179]
Something (unknown) was wrong with my previous test, which created a small library that ran twice slower (I cannot find where I opened this discussion in order to reference it here).

Now I implemented it as needed, and it runs faster! (The library is only marginally smaller.)
It seems the speed factor depends on the number of calls to functions that are not exported.
On the `fixes` and `fix-long` batches, it is about ~2-3%.

I tried to compile on macOS before removing `link-grammar.def`, and got a warning that the following are not exported:
``` text
link-grammar/dict-common/dict-api.h:	Dict_node * dictionary_lookup_list(const Dictionary, const char *);
link-grammar/dict-common/dict-api.h:	bool dictionary_word_is_known(const Dictionary, const char *);
link-grammar/dict-common/dict-api.h:	void free_lookup_list(const Dictionary, Dict_node *);
link-grammar/dict-common/dict-api.h:	bool boolean_dictionary_lookup(const Dictionary, const char *);
link-grammar/dict-file/read-dict.h:	void print_dictionary_data(Dictionary dict);
```
I propose that I just export them using `link_public_api`. On `boolean_dictionary_lookup()` I can add the `deprecated` attribute.

If this sounds OK, I will send a PR.

**Comment by linas** [comment]
Suppose instead there is a define
```
# define link_experimental_api(x) __attribute__((visibility("default")))
```
with a note: 
```
// Users are discouraged from using functions in the experimental API, unless they are
// willing to commit to the possibility that these functions may change without notice or
// may simply be removed at any time.
```
Just remove `boolean_dictionary_lookup` -- I just now fixed the one and only place where it was being used.

**Comment by ampli** [comment]
`print_dictionary_data()` is also problematic. It is defined in `link-grammar-def` but its prototype is in `read-dict.h` which not public.
I will not handle that for now.

**Comment by ampli** [comment]
The current comment on this function says:
``` c
/**
 * Declaration of dictionary-related functions that link-grammar users
 * are free to use in their applications.  That is, these are a part of
 * the public API to the link-parser system.
 */
```
I.e. the current comment says they are not experimental.

in any case, I added to `link-features.in` the following:
``` c
/* Users are discouraged from using functions in the experimental API,
 * unless they are willing to commit to the possibility that these functions
 * may change without notice or may simply be removed at any time. */
#define link_experimental_api(x) link_public_api(x)
```
so eventually we will be able to use it for the API of the `generate` branch.

I said:
> `print_dictionary_data()` is also problematic. It is defined in `link-grammar-def` but its prototype is in `read-dict.h` which not public.
> I will not handle that for now.

If needed it can be moved to `dict-api.h` and made public.

**Comment by ampli** [comment]
`From `dict-api.h`:
``` c
/* XXX the below probably does not belong ...  ?? */
Dict_node * insert_dict(Dictionary dict, Dict_node * n, Dict_node * newnode);
```
Is it being used in some program?

Because I have many more other fixes in the queue, I will leave unresolved this and the rest of the things I mentioned above and will send a PR anyway. If needed I will fix it before or after it is applied.

**Comment by linas** [comment]
Some of what is in `dict-api.h` is meant to be public, and some, not so much. 

`print_dictionary_data()` is not used in any code outside of link-grammar. It probably ended up in `ink-grammar-def ` during a debugging session, which was not cleaned up afterwards.

`insert_dict()` is not used in any code outside of link-grammar. However, my strategic vision is contents of the AtomSpace should be convertible to dictionary entries, in a bi-directional fashion, at run-time, so that a dictionary created within the AtomSpace can be directly accessed by link-grammar at runtime. Exactly how this would work, I don't yet know. Whether `insert_dict()` would be needed for this case, I don't know. So it can be removed. 

Also: for a while, I thought that the file-backed dictionary code, and the sqlite-backed dictionary code would each be in shared libraries, independent of `liblink-grammar.so`, and that they would be dynamically linked/loaded as needed. This was never done, as it became pointless complexity. Should an atomspace-backed dictionary be it's own shared library? Or maybe its just better to leave `liblink-grammar.so` as-is, and use the public API to construct a dictionary, and hand it over? If the dictionary is changing every few minutes, how should that be handled? These are low-priority questions and can be left unresolved; they just give a flavor of what I wanted to do.

**Comment by ampli** [comment]
> Should an atomspace-backed dictionary be it's own shared library? Or maybe its just better to leave `liblink-grammar.so` as-is, and use the public API to construct a dictionary, and hand it over? If the dictionary is changing every few minutes, how should that be handled?

If it is integrated with the LG library, I guess a benefit may be that it can change the dict dynamically as a response to linkages it tries. But anyway `insert_dict()` cannot be directly used for that. This is a complex issue...

(Anyway, I am now debugging the `visibility` code on a macOS, and as usual there, all sorts of strange problems happen.)
