### ISSUE TITLE
Vala VAPI Bindings, what to test/do before pull request?

### ISSUE THREAD

**Issue by kmwallio** [opencog/link-grammar#1180]
Hello,

I'm working on some [Vala bindings](https://github.com/kmwallio/link-grammar-vapi) for link-grammar. There's some issues with the char ** return values converting to string arrays in Vala. I'm not sure how to fix them myself, or if it's fine to exclude from the binding for now.

But I was looking at [the tests](https://github.com/opencog/link-grammar/tree/master/tests) and it seems like most of it is for making sure it doesn't crash. The [Python tests](https://github.com/opencog/link-grammar/blob/master/bindings/python-examples/tests.py) seem pretty verbose.

Is there a checklist or recommendation for minimal testing before sending a pull request with a new binding?

Thank you for your time and providing such a great project!

**Comment by linas** [comment]
Hi Miles!

On Mon, Apr 5, 2021 at 7:28 PM Miles Wallio ***@***.***>
wrote:

> Hello,
>
> I'm working on some Vala bindings
> <https://github.com/kmwallio/link-grammar-vapi> for link-grammar.
>
Huh!  I have fond memories of GObjects; for me, they were the best-of-c++
without the rest of c++ ... but I'd never heard of vala before.

> There's some issues with the char ** return values converting to string
> arrays in Vala. I'm not sure how to fix them myself, or if it's fine to
> exclude from the binding for now.
>
I'm not sure if this is a technical issue, or a documentatio issue. The API
is documented in
https://www.abisource.com/projects/link-grammar/api/index.html

The only char** I see is in linkage_get_words() .. different linkages might
have different words in them, for example, if there is a typo, then the
spell-guesser will offer up different word-choices.

> But I was looking at the tests
> <https://github.com/opencog/link-grammar/tree/master/tests> and it seems
> like most of it is for making sure it doesn't crash. The Python tests
> <https://github.com/opencog/link-grammar/blob/master/bindings/python-examples/tests.py>
> seem pretty verbose.
>
Yep. Historically, there have not been any unit tests. So far, that seems
OK, since more-or-less nothing ever breaks. The python tests are more
verbose, because python is the visual-basic of the 21st century, and it
drags around that mentality wherever it goes.

> Is there a checklist or recommendation for minimal testing before sending
> a pull request with a new binding?
>
No.  The recommendation is to stick your name on it in some prominent way,
and to make vague promises to make sure the bindings don't bit-rot over the
years. If someone writes an email and says "the vala bindings don't work" I
can't be the one to help that person.

Send a pull req any time. They'll be in version 5.9.0 which is either weeks
or months away, depending on the local weather.

> Thank you for your time and providing such a great project!
>
Heck, thank you for this email!

-- Linas

**Comment by linas** [comment]
Closing; the Vala bindings are now distributed as part of version 5.9.0, issued just today.  The tarball is at

https://www.abisource.com/downloads/link-grammar/5.9.0/link-grammar-5.9.0.tar.gz

Please download and test; I presume everything should work.   Sorry for not notifying you that a new release was coming soon; there was a lot of exciting work that went into this one. If you do find bugs, open a new pug report, or, better yet, a pull req. If the bug is serious enough to require a new release, just say so; it is not particularly hard to spin new releases.
