### ISSUE TITLE
link-grammar 5.10.0 failed to build

### ISSUE THREAD

**Issue by chenrui333** [opencog/link-grammar#1246]
```
Making install in python
  CXX      _clinkgrammar_la-lg_python_wrap.lo
  CXXLD    _clinkgrammar.la
 ../.././install-sh -c -d '/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar'
 ../.././install-sh -c -d '/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
 ../.././install-sh -c -d '/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar'
 /usr/bin/install -c -m 644 ./linkgrammar.pth '/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
install: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar.pth: Operation not permitted
make[3]: *** [install-pkgpypathPYTHON] Error 71
make[3]: *** Waiting for unfinished jobs....
mkdir: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar: Operation not permitted
mkdir: /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/linkgrammar: Operation not permitted
make[3]: *** [install-pkgpyexecLTLIBRARIES] Error 1
make[3]: *** [install-pkgpythonPYTHON] Error 1
```

full error log, https://github.com/Homebrew/homebrew-core/runs/3516136659
relates to https://github.com/Homebrew/homebrew-core/pull/84708

**Comment by chenrui333** [comment]
might be more of an issue on the homebrew side.

**Comment by linas** [comment]
Reposting what I said there (in Homebrew/homebrew-core#84708)

This is the same install path that python3 has used for the last 8+ years; it has not changed. It's the recommended default install path on "conventional" python3 installations (to the best of my understanding). I guess you are saying its different somehow on Apple?

I believe that link-grammar has not altered this install path since the inception; we're not doing anything different here, than before. So I'm guessing that something else changed, in some other package, that is having a side-effect of causing this to fail.

Disclaimer: I have found that python package installs to be a confusing issue, with the core python people providing conflicting recommendations, and so getting this correct by default has long been a rather tricky endevour. In other words, what I say above might be wrong.
