### ISSUE TITLE
5.10.0 fails to build

### ISSUE THREAD

**Issue by limburgher** [opencog/link-grammar#1248]
See attached log; problem with include path.
[build.log](https://github.com/opencog/link-grammar/files/7122303/build.log)

**Comment by linas** [comment]
Looking. You've enabled the perl bindings, which are usually disabled. They're disabled because the traditional answer has been to use Danny Brian's Lingua::LinkParser bindings. ... but he has not touched those in 7 years, so they might be bitrotted.  We've spent no effort at all to make the perl bindings here look nice, so the failure is not surprising.

Are you building an official RPM for fedora?

**Comment by limburgher** [comment]
I am the Fedora maintainer, yes. I could simply disable perl, as I don't find any packages in Fedora that require it.

**Comment by linas** [comment]
I just fixed it. If you wait about half an hour, I'll publish version 5.10.1 with the fix in it.  Other than patching configure, it seems fedora is not carrying any other patches, is that right?

**Comment by linas** [comment]
Closing, new version at https://www.abisource.com/downloads/link-grammar/5.10.1/link-grammar-5.10.1.tar.gz

**Comment by limburgher** [comment]
Looks great, thank you!
