### ISSUE TITLE
Dictionary 'ru/4.0.dict': No locale definition

### ISSUE THREAD

**Issue by Antipire** [opencog/link-grammar#1252]
Hello everyone! Im currently using Ubuntu 18.04, Link Grammar Version: 5.3.16, python3.6. Whem I'm trying to load dictionaries with `lg.Dictionaty('ru')` error in the title shows up and no result is printed. So I tried many solutions in "Issues" section and no one of them helped. I made all strictly to the instruction and installed all necessities libs. (Why older version? Because 5.10 version can't pass python tests.py, and no sultion for this found)

Chapter 1. `No module named 'linkgrammar'.`
When I first time made linkgrammar and tried to run simple python3 script, there was no module installed. I checked dist-packages and so on and didnt find lib. apt-get install python3-link-grammar helped. Strange solution, so maybe I did something wrong.

Chapter 2. `No locale definition`
After installing package I wrote above, python can see linkgrammar, but can't see dictionaries. When I'm trying to use any language (e. g. ru, en...) shows up `link-grammar: Info: Dictionary 'en/4.0.dict': No locale definition - "en_US.UTF-8" will be used.
`. I checked `/usr/local/share/link-grammar` and saw, that all needed languages are installed. Unfortunately, no solution in Issues tab was found, thats why I'm writing this post.

P.S. Need to mention that I'm not using Docker.

Thank You in advance.

**Comment by ampli** [comment]
> `Dictionary 'ru/4.0.dict': No locale definition`

This is an informational message only - not an error. It means the dictionary has been actually **found**, but you don't have the locale `ru_RU.UTF8` (see `dictionary-locale` at the start of `ru/4.0.dict`) installed in your system.

> Unfortunately, no solution in Issues tab was found, thats why I'm writing this post.

Solution: You can safely ignore that, or just install this locale (Google for **ubuntu install locale**).

> Whem I'm trying to load dictionaries with `lg.Dictionaty('ru')` error in the title shows up and no result is printed.

Which result do you expect to be printed by loading a dictionary?

> link-grammar: Info: Dictionary 'en/4.0.dict': No locale definition - "en_US.UTF-8"

I guess that it will then use `C.UTF8` because `en_US.UTF-8` is actually missing. You may install `en_US.UTF-8` too.

> Because 5.10 version can't pass python tests.py

Do you mean 5.10.2?
Which test fails?

> apt-get install python3-link-grammar helped

Have you installed `link-grammar` by `apt-get install link-grammar` or by compiling the tar source code?
If you installed it by `apt-get`, then installing its Python binding should indeed be done by `apt-get install python3-link-grammar` (no other way).
