### ISSUE TITLE
Simple usage for link-generator and its crash

### ISSUE THREAD

**Issue by DaddyWesker** [opencog/link-grammar#1281]
Hello!

I've been trying to launch link-generator on my laptop and I've faced some problems.

1. I haven't found any example on link-generator usage. Maybe I've missed something? Could you point me to it? 
2. When just launching 
`link-generator --count=2 --language=en`
I'm getting `Killed` after a while. Could it be related to
a) I have only 16 gb of ram
b) i wasn't been able to npm install node.js folder.

Thanks in advance

**Comment by linas** [comment]
Here's a short answer:
1. link-generator remains "experimental", subject to change, and currently under-documneted. Although there is a man-page on it (in the man directory).

2.a. Yes, probably. In the current design, the RAM usage is explosive when used with large dictionaries. It might be possible to reduce this dramatically, by sorting words into classes; this would require extensive changes to the infrastructure. These changes need to be done anyway, as we need to export a list of words in each word-class.  Stuff like this is why its "experimental".

2.b. Open a new bug report for npm. However, at this time, npm is "unmaintained", unless you can find the original authors and convince them to hack on it. (you probably know more about npm than I do.)

I'm hoping @ampli can say more.

**Comment by ampli** [comment]
> I've been trying to launch link-generator on my laptop and I've faced some problems.

> 2\. a) I have only 16 gb of ram

Only the amount of virtual memory matters for the functionality of `link-generator`. If you have more RAM, it just runs faster (with small RAM it runs slowly due to swapping, but SSD disks and/or compressed swap pages may help).

Use (from a console window)
`systeminfo | find/i "virtual memory"`
to see how much virtual memory you have. Try to increase its maximum size to 32GB.
See for example [Increasing Virtual Memory on Windows](https://www.x-plane.com/kb/increasing-virtual-memory-on-windows/).

Also, the default sentence length to generate is 6. For `en`, generation using 6 wildcard words needs much memory. First, try to use `--length=2` and increase the sentence length if it works. In this way you can find out how many wildcard words work for you.  For longer sentences, you may try to specify several words using an input sentence template with fixed words, so the number of wildcard words is kept small.
`link=generator ---length=0 --language=en`
At the prompt enter, for example:
`This \* a \*.`
In addition, to save memory on wildcard words, you can specify them with a subscript such as: `\*.n`, or even more fully like `sub\*.n`.

**Comment by DaddyWesker** [comment]
@linas THanks for the answer. 
1. GOt it. THough looking into the man doesn't helped me a lot at the first time.
2a. Thanks for the explanation
2b. No, i don't =) If it isn't necessary to run link-generator from the console then it is fine for me.

**Comment by DaddyWesker** [comment]
@ampli 
Thanks for the answer!

I'm on the linux mint, not windows. SO, it is `swapon --show` for me. It is 16 gb. I'll try to extend to 32 gb and test again and will get back to you.

**Comment by DaddyWesker** [comment]
After extending swap to 32 gb link-generator works with command `link-generator --length=0 --language=en`. Thanks

So, what exactly this `n` means in `\*.n`? I thought it should restrict generated words to have 'n' on the end, but it isn't.

**Comment by ampli** [comment]
> So, what exactly this `n` means in `\*.n`? I thought it should restrict generated words to have 'n' on the end, but it isn't.

By default `link-generator` strips the subscripts. To see them use `--leave-subscripts`.

BTW, the implemented restrictions are currently very primitive, and they are included only because they just happen to be supported in the library (for the `!` command of `link-parser`).

**Comment by linas** [comment]
@DaddyWesker what are you using the generator for?

I want to change the API "someday" (that fabled future "someday") so that the output replaces the wild-cards by the name of a word-class, and then separately, it provides you with a list of all words that belong to that class (together with a weight or log-probability of membership.) That way, you can use your own algos to perform the final word selection, instead of letting the tool just randomly pick one.  Exactly how to make this work elegantly from a command-line tool remains mysterious, at best.

**Comment by DaddyWesker** [comment]
@linas 
Actually, I was just looking for libraries able to generate sentences out of some sort of templates. Like AMR templates. And i was suggested to see your link-generator.

**Comment by linas** [comment]
@ampli 

>>  It might be possible to reduce this dramatically, by sorting words into classes; this would require extensive changes to the infrastructure.
>
> This is already fully implemented. 

I knew that, so I am not sure what I was thinking.  Brainstorming wildly: 
* Is it possible to do more pruning with expressions, before they are expanded into disjuncts? 
* Maybe one could have disjunct classes: for example, if you discover that the connector `A-` cannot connect, then you can deduce that all disjuncts with `A-` cannot connect.   (Maybe the current pruning code already does this. I haven't looked at this in ages, and have forgotten any and all details.)

**Comment by ampli** [comment]
> * Is it possible to do more pruning with expressions, before they are expanded into disjunct?

More pruning with expressions may only save CPU in `power_prune()`, which would need to scan fewer disjunct.
But it is very fast anyway. Nevertheless, I tried to exploit the fact that two deep connectors cannot connect, and mark expression connectors that are always deep. However, there are too few of them in general due to optional connectors, and no extra pruning results.

I have an old power_prune()` WIP that detects more cross-linking and eliminates ~5% more disjunct. Surprisingly, it doesn't speed up even long sentences, maybe because the removed disjuncts are not accessible anyway during parsing. But I didn't test that in generation mode. This WIP is currently so I need to restore it to a working state for testing that.

> if you discover that the connector A- cannot connect, then you can deduce that all disjuncts with A- cannot connect.

This is actually what `power_prune()` does.

I have several other ideas for speeding up by reducing the memory footprint (some are WIPs that I need to convert to PRs).

I can also implement the `max_memory` parse option as I mentioned in PR #1024 and elsewhere. The idea is to not grow the Table_connector array if the resulted total memory would be > max_memory. This would slow the generation but at least not abort. Using a prime number array size (instead of a power of 2) may also help.

Another option I investigate is ways to drastically reduce the size of the Table_connector array (which takes most of the memory during generation).

Dumping memory stats on sentence delete or SIGTERM could also be helpful for insights (especially on SIGTERM due to OOM).

**Comment by linas** [comment]
If a pattern has more than 2 or 3 wild-cards in it, the user is typically not interested in an exhaustive list of all possibilities, which would number in the millions, if not trillions. In this case, the kind of "global" optimization that the LG parser does is not needed, and is not optimal. Some local approach could (should) be smaller, faster. 

Say the pattern has 3 stars in it, and the user has asked for 1000 sentences to be generated. So, pick one star, any one, and randomly discard all but 10 disjuncts on it. Now, if one could (but LG doesn't work this way) attach a second star, prune, and keep 10 random disjuncts on the second star.  Repeat for the third star, and you should now have 10*10*10 sentences. 

But LG doesn't work that way, so maybe this: before starting, pick 10 random disjuncts for each wildcard. After pruning, there might be zero valid parses left, because out of these random choices, none of them can connect up.  So try again with 20 randomly selected DJ's on each -- maybe you get 2 or 5 valid sentences. Repeat with 40, 80, 160 ... until you get enough results.

You can get fancy: instead of a step size of 2 (giving the 10,20,40,80... above), you could have a step size of 2 pow (1/N) where N is the number of wild-card stars.

**Comment by ampli** [comment]
> But LG doesn't work that way, so maybe this: before starting, pick 10 random disjuncts for each wildcard. After pruning, there might be zero valid parses left, because out of these random choices, none of them can connect up. So try again with 20 randomly selected DJ's on each -- maybe you get 2 or 5 valid sentences. Repeat with 40, 80, 160 ... until you get enough results.

This is indeed a good idea, and it is one of the ways I explore.
(But first I would like convert some bug fixes and new ideas to PRs.)

BTW, what causes a heavy memrey/CPU load is many wildcards in a row.  If there are intervening fixed words (or words with constraints like `super*.a`, there is a significant pruning that removes most of the disjuncts.

**Comment by linas** [comment]
> many wildcards in a row

Yes. Well, the user requirements are vague.  I was using it with 5-10 stars in a row, but with small, "artificial" languages. It worked well, but I stopped using the artificial languages for unrelated reasons. 

The  long term goal would be to "write a paragraph or two (5 or 10 sentences) about everything that you know about food and cooking". I can provide a large network of "facts" about food and cooking (say, a list of foods, a perhaps by geographical location, perhaps major ingredients "brandy is made from distilled fermented fruit")  so the task is to "serialize" that network into a string of words; basically, a random walk through the network, but a grammatically correct one.   An intermediate-term goal might be "write a sentence with these words in it: "brandy, make, fruit, fruit-modifier: fermented, fermented-modifier: distilled", because that kind of knowledge is available.   To deal with morphology, it would have to be something like this: "use the word 'make' or 'making' or 'made', pick one".  Wild-cards could be limited: for wild-cards, use "the", "a", "this", "is", "was", "of", "in", "yet" ...filler words needed to make viable parses. 

That's the day-dream. Obviously, this goes far beyond the interfaces that LG currently has.

**Comment by linas** [comment]
closing; this seems to be a stale bug report. If there are new issues, please open new bug report.

**Comment by ampli** [comment]
I still need to implement this:
>>>But LG doesn't work that way, so maybe this: before starting, pick 10 random disjuncts for each wildcard. After pruning, there might be zero valid parses left, because out of these random choices, none of them can connect up. So try again with 20 randomly selected DJ's on each -- maybe you get 2 or 5 valid sentences. Repeat with 40, 80, 160 ... until you get enough results.

>(But first I would like convert some bug fixes and new ideas to PRs.)
