### ISSUE TITLE
realloc(): invalid next size error

### ISSUE THREAD

**Issue by leungmanhin** [opencog/link-grammar#136]
A sentence from Simple English Wikipedia causes the link-parser to crash when parsing it:

In Buddhism there are 84 Mahasiddhas: Acinta, Ajogi, Anangapa, Aryadeva, Babhaha, Bhadrapa, Bhandepa, Bhiksanapa, Bhusuku, Camaripa, Campaka, Carbaripa, Catrapa, Caurangipa, Celukapa, Darikapa, Dengipa, Dhahulipa, Dharmapa, Dhilipa, Dhobipa, Dhokaripa Dombipa, Dukhandi, Ghantapa, Gharbari, Godhuripa, Goraksa, Indrabhuti, Jalandhara, Jayananda, Jogipa, Kalapa, Kamparipa, Kambala, Kanakhala, Kanhapa, Kankana, Kankaripa, Kantalipa, Kapalapa, Khadgapa, Kilakilapa, Kirapalapa, Kokilipa, Kotalipa, Kucipa, Kukkuripa, Kumbharipa, Laksminkara, Lilapa, Lucikapa, Luipa, Mahipa, Manibhadra, Medhini, Mekhala, Mekopa, Minapa, Nagabodhi, Nagarjuna, Nalinapa, Naropa, Nirgunapa, Pacaripa, Pankajapa, Putalipa, Rahula, Saraha, Sakara, Samudra, Santipa, Sarvabhaksa, Savaripa, Syalipa, Tantepa, Tantipa, Thaganapa, Tilopa, Udhilipa, Upanaha, Vinapa, Virupa, Vyalipa.

With this error:
*** Error in `/home/manhin/link-grammar-5.2.5/link-parser/.libs/lt-link-parser': realloc(): invalid next size: 0x0000000006b23e90 ***
Aborted (core dumped)

**Comment by yantrabuddhi** [comment]
I get the same error with this sentence:
"And yet he should be always ready to have a perfectly terrible scene, whenever we want one, and to become miserable, absolutely miserable, at a moment’s notice, and to overwhelm us with just reproaches in less than twenty minutes, and to be positively violent at the end of half an hour, and to leave us for ever at a quarter to eight, when we have to go and dress for dinner when, after that, one has seen him for really the last time, and he has refused to take back the little things he has given one, and promised never to communicate with one again, or to write one any foolish letters, he should be perfectly broken-hearted, and telegraph to one all day long, and send one little notes every half-hour by a private hansom, and dine quite alone at the club, so that every one should know how unhappy he was"

**Comment by bgoertzel** [comment]
Great sentence!! ;)

On Wed, Jul 8, 2015 at 1:23 PM, Mandeep <notifications@github.com> wrote:

> I get the same error with this sentence:
> "And yet he should be always ready to have a perfectly terrible scene,
> whenever we want one, and to become miserable, absolutely miserable, at a
> moment’s notice, and to overwhelm us with just reproaches in less than
> twenty minutes, and to be positively violent at the end of half an hour,
> and to leave us for ever at a quarter to eight, when we have to go and
> dress for dinner when, after that, one has seen him for really the last
> time, and he has refused to take back the little things he has given one,
> and promised never to communicate with one again, or to write one any
> foolish letters, he should be perfectly broken-hearted, and telegraph to
> one all day long, and send one little notes every half-hour by a private
> hansom, and dine quite alone at the club, so that every one should know how
> unhappy he was"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/link-grammar/issues/136#issuecomment-119437503>
> .
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by ampli** [comment]
I have just sent a pull request (#137) that fixes this problem.

The first sentence is still not displayed, due to an error "The diagram is too high.".
(This can be "fixed" by increasing MAX_HEIGHT in link-grammar/print.c from 30 to, say, 60.)
But if you use the API you will still be able to find all the links.

**Comment by leungmanhin** [comment]
Thanks @ampli
