### ISSUE TITLE
Crash when parsing a lot of sentences continuously

### ISSUE THREAD

**Issue by leungmanhin** [opencog/link-grammar#141]
When parsing sentences from Simple English Wikipedia via RelEx continuously, it crashed at some point with this error:

*** Error in `java': free(): invalid pointer: 0x00007f63ea9403f0 ***

A memory leak perhaps...?

**Comment by linas** [comment]
Need a stack trace to debug.  Also, please use version 5.3.1

The problem that I'm seeing is that relex is leaking memory like crazy -- uses up 8GBytes in 24 hours. https://github.com/opencog/relex/issues/228  I haven't seen any crashes.

I'm closing this, because without a stack trace, there's nothing to be done.
