### ISSUE TITLE
Crash when parsing a sentence -- Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by leungmanhin** [opencog/link-grammar#146]
Another weird sentence that causes the link-parser to crash:

```
"To" It's to let; there's a notice on the door
```

Got this error:
```
Assertion (0 < max_words--) failed at ../../link-grammar/tokenize.c:2715: Too many words (it may be an infinite loop)

Illegal instruction (core dumped)
```

**Comment by ampli** [comment]
I have just now sent a pull request (#148) that fixes this problem.
The problem depended on `"To"` to match a regex (in this case EMOTICON) in two ways
(`"To"` and `"To`).

The offending sentence could be reduced to:
`"T" to  let there a notice`

BTW (not related to this crash):
If link-parser could pop-up missing words, it would fully parse this sentence as:
```
    +----------------------------Xx---------------------------+           +------MVp-----+         
    +----------Wd----------+   +----IV--->+                   +---->WV--->+---Ost--+     +---Js---+
    |            +----CO---+-Ss+-TO-+-I*t-+-----Os----+       +-Wd-+-SFst-+  +Ds**c+     |  +Ds**c+
    |            |         |   |    |     |           |       |    |      |  |     |     |  |     |
LEFT-WALL "To"[!EMOTICON] it 's.v to.r let.v-d UNKNOWN-WORD.n ; there.r 's.v a notice.s on the door.n 
```

**Comment by linas** [comment]
Hmm.  At one point, I invented a way of adding missing words. Unfortunately, I did not write it down, and mostly forgot how to implement it.

The above sentence, however, illustrates the danger of adding words: "It's to let" is a perfectly valid sentence in British English. It means "It's for rent".   There's not missing object.

**Comment by ampli** [comment]
I would like to add this sentence to 4.0.fixes.batch. Should it be considered as correct or incorrect?

**Comment by linas** [comment]
`It's to let; there's a notice on the door.`  is correct.

`"To" It's to let; there's a notice on the door.`  is nonsense of some kind; I don't know what it is supposed to mean.

**Comment by ampli** [comment]
The point is that "To" is currently tokenized by the EMOTICON regex.
```
EMOTICON: /^[[:punct:];BＣ☆ಠ●＠◎～][-!"#$%&'()+,:;<=>?@[\\^_`{|}~<cdDLmoOpPSTvXಠっ○ 。゜✿☆＊レツ◕●≧∇≦□◇＠◎∩ω旦ヨ彡ミ‿◠￣ー～━-]+$/
```

Among many other things, anything that matches
`^[^[[:punct:]BC]["@,cdDLmoOpPSTvX]`
is considered to be EMOTICON. Including letters there is problematic, as they may match real words.
So this sentence currently parses also in that way:
```
    +-------------->WV-------------->+         
    +------------Wd------------+     +---Ost--+
    |             +-----CO-----+-Ss*b+  +Ds**c+
    |             |            |     |  |     |
LEFT-WALL "Tom,"[!EMOTICON] this.p is.v a  test.n 
```
In the same manner, the current dict considers prepending correct sentences by `"To"`  as correct...
So if it accepts `It's to let;` to be correct, then it would currently accept `"To" It's to let;` as correct.

The question is if this is fine, or we need to fix it.

BTW, if negative matches could be defined (as a kind of primitive lookahead), as in:
REGEX: -/something/
Then things like "word" could be avoided by putting a thing similar to this before the current EMOTICON definition:
EMOTICON: -/^".*"$/
In such a manner improper matching of other regex'es, such as ROMAN-NUMERAL-WORDS matching the empty string, could be fixed.

But I guess all of that is not very important.

BTW, the problem this sentence caused is not only because `"To"` and `"To` match EMOTICON, but also because `To` matches a word, and its lc version is tokenized too, a thing that creates a "complex" wordgraph that got handled incorrectly.

**Comment by linas** [comment]
... I don't know. 

Without the quotes: `Tom, this is a test`  is a valid sentence; `Tom` should be recognized as a given name. (someone is telling Tom, or reminding him, that 'this is a test'.  Thus the clause-opener link CO is correct.    With quotations, it is just some weird junk ...

**Comment by ampli** [comment]
>Without the quotes: Tom, this is a test is a valid sentence; Tom should be recognized as a given >name. (someone is telling Tom, or reminding him, that 'this is a test'. Thus, the clause-opener link >CO is correct.) With quotations, it is just some weird junk ...

As usual I was not clear enough. My point was another one, and it is regarding the EMOTICON regex (and several other ones) too broad, and while useful many times, the needs to be restricted in what they match, However, the current mechanism used to express regex'es is too limited. But it seems it can be mostly fixed by the shown idea of negative regex'es, an extension that is **easy to implement**.

In any case, I think that any regex match needs to get a **high cost** . In the shown sentence, the linkages with EMOTICON are the first ones....
(I would even say a regex match needs to incur a cost only if it cannot be interpreted as another valid token - a thing that cannot be implemented by the current library infrastructures. But I fear my intention in that may be rather unclear.).

But what you said raises another unrelated thing.
Due to alternatives, and because currently quotes are essentially ignored, the linkages
also includes the one of the sentence without the quotes. So lets try it directly:
```
linkparser> Tom, this is a test
Found 14 linkages (14 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 1.00 LEN=9)

    +-----Xx----+--->WV--->+---Osm--+
    +---Wa--+   +-Wd-+-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL tom.s , this.p is.v a  test.n 

Press RETURN for the next linkage.
```

The next 9 linkages include other various (strange?) interpretations.  Only the 4 last ones are with CO (only 2 of them with the expected Tom.m,), and maybe the costs should be arranged so they will be the first ones.

Here is the full linkage list:
```
linkparser> Tom, this is a test
Found 14 linkages (14 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 1.00 LEN=9)

    +-----Xx----+--->WV--->+---Osm--+
    +---Wa--+   +-Wd-+-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL tom.s , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 2, cost vector = (UNUSED=0 DIS= 1.00 LEN=9)

    +-----Xx----+--->WV--->+---Osm--+
    +---Wa--+   +-Wd-+-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL Tom.m , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 3, cost vector = (UNUSED=0 DIS= 1.00 LEN=9)

    +-----Xx----+--->WV--->+---Ost--+
    +---Wa--+   +-Wd-+-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL tom.s , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 4, cost vector = (UNUSED=0 DIS= 1.00 LEN=9)

    +-----Xx----+--->WV--->+---Ost--+
    +---Wa--+   +-Wd-+-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL Tom.m , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 5, cost vector = (UNUSED=0 DIS= 2.00 LEN=9)

    +------Xx-----+--->WV--->+---Osm--+
    +---Wa---+    +-Wd-+-Ss*b+  +Ds**c+
    |        |    |    |     |  |     |
LEFT-WALL tom.n-u , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 6, cost vector = (UNUSED=0 DIS= 2.00 LEN=9)

    +------Xx-----+--->WV--->+---Ost--+
    +---Wa---+    +-Wd-+-Ss*b+  +Ds**c+
    |        |    |    |     |  |     |
LEFT-WALL tom.n-u , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 7, cost vector = (UNUSED=0 DIS= 2.00 LEN=13)

    +--------->WV--------->+         
    +-------Wd-------+     |         
    |       +---COp--+     +---Osm--+
    |       +-Xc+    +-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL tom.a , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 8, cost vector = (UNUSED=0 DIS= 2.00 LEN=13)

    +--------->WV--------->+         
    +-------Wd-------+     |         
    |       +---COa--+     +---Osm--+
    |       +-Xc+    +-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL Tom.m , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 9, cost vector = (UNUSED=0 DIS= 2.00 LEN=13)

    +--------->WV--------->+         
    +-------Wd-------+     |         
    |       +---COp--+     +---Ost--+
    |       +-Xc+    +-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL tom.a , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 10, cost vector = (UNUSED=0 DIS= 2.00 LEN=13)

    +--------->WV--------->+         
    +-------Wd-------+     |         
    |       +---COa--+     +---Ost--+
    |       +-Xc+    +-Ss*b+  +Ds**c+
    |       |   |    |     |  |     |
LEFT-WALL Tom.m , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 11, cost vector = (UNUSED=0 DIS= 6.00 LEN=10)

  +---COp--+     +---Osm--+
  +-Xc+    +-Ss*b+  +Ds**c+
  |   |    |     |  |     |
tom.a , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 12, cost vector = (UNUSED=0 DIS= 6.00 LEN=10)

  +---COa--+     +---Osm--+
  +-Xc+    +-Ss*b+  +Ds**c+
  |   |    |     |  |     |
Tom.m , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 13, cost vector = (UNUSED=0 DIS= 6.00 LEN=10)

  +---COp--+     +---Ost--+
  +-Xc+    +-Ss*b+  +Ds**c+
  |   |    |     |  |     |
tom.a , this.p is.v a  test.n 

Press RETURN for the next linkage.
linkparser> 
	Linkage 14, cost vector = (UNUSED=0 DIS= 6.00 LEN=10)

  +---COa--+     +---Ost--+
  +-Xc+    +-Ss*b+  +Ds**c+
  |   |    |     |  |     |
Tom.m , this.p is.v a  test.n 

linkparser> 
```

**Comment by ampli** [comment]
>The above sentence, however, illustrates the danger of adding words: "It's to let" is a perfectly valid >sentence in British English. It means "It's for rent". There's no missing object.

Is not it a similar danger to the one the spell correction feature has, in case a word is not in the LG dict but also not in the speller dictionary? (In English such an unknown word often matches a regex and thus not pass a spell correction, and this problem is avoided.)

BTW, the API can be extended to indicate the original word for words that passed a spell correction.
Currently there is no programmatic way to find that.

**Comment by linas** [comment]
Yes,

I guess linkage 8 looks like the first "classically correct" parse, although parse 2 is essentially equivalent to it.   Bigger problem is that "tom" the common noun (tom-tom drum) is competing with the far-more common given name Tom.
 
Yes, the emoticon regex can/should be fixed, and a negative match seems OK for that.

Yes, you are welcome to extend the API to get the words that correspond to a spell-corrected segment.

**Comment by leungmanhin** [comment]
It's fixed, thanks!
