### ISSUE TITLE
crash in tokenizer!

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#238]
Apply the following change to the dict:
```
--- a/data/en/4.0.affix
+++ b/data/en/4.0.affix
@@ -31,7 +31,8 @@
 
 % Prefixes
 % Y'gotta Y'gonna
-y': PRE+;
+% coffe w/milk
+y' w/: PRE+;

```
Verify that LG works:
```
linkparser> Y'gotta go with me
    +---->WV---->+                 
    +--Wd--+-Sp*i+--I*t--+-MVp+-J-+
    |      |     |       |    |   |
LEFT-WALL y' gotta.v-d go.v with me 

linkparser> I take my coffee w/ milk
                 +---------MVp--------+      
    +---->WV---->+------Ou-----+      |      
    +--Wd--+-Sp*i+     +--Dmu--+      +--Ju-+
    |      |     |     |       |      |     |
LEFT-WALL I.p take.v my.p coffee.n-u w/ milk.n-u 

linkparser> I take my coffee w/milk
link-grammar: 
Assertion (temp_wend>w) failed at ../../link-grammar/tokenize.c:1706: strip_right: unexpected empty word

Illegal instruction
```

**Comment by linas** [comment]
Oh, heh: minor correction: the parse of  `I take my coffee w/ milk` only works if `4.0.affix` was not modified. If it is modified, then it crashes with or without the bank space between `w/` and the rest of the word.

**Comment by linas** [comment]
its line 1706 not 1701 if I use the current github source

**Comment by ampli** [comment]
I looks like GitHub has a bug regarding pushing the same branch again, when it referes to an issue...
It shows an additional reference instead of only the last one.

**Comment by linas** [comment]
OK, after updating, the printing seems a little strange.  First, this seems normal:
```
linkparser> Y'gonna help me?
Found 1 linkage (1 had no P.P. violations)
	Unique linkage, cost vector = (UNUSED=0 DIS= 0.00 LEN=5)

    +------------Xp------------+
    +---->WV----+              |
    +--Wd--+Sp*i+--I*t--+-Ox-+ |
    |      |    |       |    | |
LEFT-WALL y' gonna.v help.v me ? 
```
notice the blank space between Y' and gonna.  But no blank space below:
```
linkparser> I take my coffee w/milk.
Found 8 linkages (8 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=10)

    +---------------------Xp---------------------+
    |            +--------MVp--------+           |
    +---->WV---->+------Ou-----+     |           |
    +--Wd--+-Sp*i+     +--Dmu--+     +--Ju-+     |
    |      |     |     |       |     |     |     |
LEFT-WALL I.p take.v my.p coffee.n-u  w/milk.n-u . 
```
If I turn on !mor then the blank appears:
```
linkparser> I take my coffee w/milk.
Found 8 linkages (8 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=10)

    +---------------------Xp---------------------+
    |            +---------MVp--------+          |
    +---->WV---->+------Ou-----+      |          |
    +--Wd--+-Sp*i+     +--Dmu--+      +--Ju-+    |
    |      |     |     |       |      |     |    |
LEFT-WALL I.p take.v my.p coffee.n-u w/ milk.n-u . 
```
 Why does w/ behave differently than Y'  ?

**Comment by ampli** [comment]
In order to create infrastructure for "clever display", the new tokenization code has the following code:
```
				case PREFIX: /* set to word= */
					sz = strlen(*affix);
					strncpy(buff, *affix, sz);
					buff[sz] = infix_mark;
					buff[sz+1] = '\0';
					if (is_contraction_word(unsplit_word->subword))
						morpheme_type = MT_CONTR;
					else
						morpheme_type = MT_PREFIX;
					break;
```
So it marks `y'` as MT_CONTR and `w/` as MT_PREFIX.
The display code currently collapses by default MT_PREFIX but not MT_CONTR.
Up to now (end even now - `w/` is still not in the master branch on GitHub) "en" did not have a prefix which is not a contraction, so this inconsistency has not been detected (collapsing MT_PREFIX spaces is done when displaying Hebrew parses.) The MT_CONTR mark is used to warn if a contraction is defined but is not in the dict (but this is maybe a wrong way to do that , as it is not general enough, see below (*)).

Solutions to the inconsistent space collapse:

1. Add some mechanism to set whether space collapse happen by default. We already have LL* links that set a default space collapse. But for things like `y'` and `w/` encoding it in the links may not be a good idea. It can still be done is some other different ways if desired.

2. Contracting the space (by default) for all kind of prefixes, including contracted words, and even for all kind of "suffix" contractions. This has currently a slight aesthetic problem, as prefix space collapse are not well-supported by the diagram drawing code (the vertical bar is before the word). 

BTW, the quoted code above would cause a bug if we would like to support a language with contractions and prefixes which have INFIX_MARK attached... I need to fix it.

(*) A general way to do it may be checking, while assigning PRE etc. from the affix file, that all the tokens in the affix file are found in the dict.

So I mentioned here 4 needed fixes (at least...). Is there a way on GitHub to make a summary of needed fixes, instead of letting them to get hidden inside issue discussions?

**Comment by linas** [comment]
Yes, -- I should have opened a new bug report !  the bug reports can be used to track work items...

**Comment by linas** [comment]
I copied to #240. For English, it should leave spaces.

**Comment by ampli** [comment]
I think I know how to do that - prefix/suffix spaces should collapse only if an INFIX_MARK is attached to them.
