### ISSUE TITLE
prefix spacing

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#240]
After updating for fix for #238, printing is odd:

OK, after updating, the printing seems a little strange.  First, this seems normal:
```
linkparser> Y'gonna help me?
Found 1 linkage (1 had no P.P. violations)
	Unique linkage, cost vector = (UNUSED=0 DIS= 0.00 LEN=5)

    +------------Xp------------+
    +---->WV----+              |
    +--Wd--+Sp*i+--I*t--+-Ox-+ |
    |      |    |       |    | |
LEFT-WALL y' gonna.v help.v me ? 
```
notice the blank space between Y' and gonna.  But no blank space below:
```
linkparser> I take my coffee w/milk.
Found 8 linkages (8 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=10)

    +---------------------Xp---------------------+
    |            +--------MVp--------+           |
    +---->WV---->+------Ou-----+     |           |
    +--Wd--+-Sp*i+     +--Dmu--+     +--Ju-+     |
    |      |     |     |       |     |     |     |
LEFT-WALL I.p take.v my.p coffee.n-u  w/milk.n-u . 
```
If I turn on !mor then the blank appears:
```
linkparser> I take my coffee w/milk.
Found 8 linkages (8 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=10)

    +---------------------Xp---------------------+
    |            +---------MVp--------+          |
    +---->WV---->+------Ou-----+      |          |
    +--Wd--+-Sp*i+     +--Dmu--+      +--Ju-+    |
    |      |     |     |       |      |     |    |
LEFT-WALL I.p take.v my.p coffee.n-u w/ milk.n-u . 
```
 Why does w/ behave differently than Y'  ?

**Comment by linas** [comment]
I just pushed a 4.0.affix with w/ in the English dict.

**Comment by linas** [comment]
sorry, I also did not use a pull request for that, it seemed minor and not worth the effort, but makes it harder to review. Should I use a pull request?

**Comment by ampli** [comment]
The best thing is that you continue to do it in a way that is most convenient to you.
In any case, I look at all the changes you do.

**Comment by ampli** [comment]
My proposed way to fix it: Collapse prefix/suffix space only if LL link involved (should eventually maybe add an affix file directive to list additional link prefixes for that purpose) **or** when there is an **INFIX_MARK** attached to the prefix/suffix.

**Comment by linas** [comment]
Yes, that seems reasonable. INFIX_MARK was sufficient for the Russian dicts. If work on Turkish heats up, then ... ?  Hard to say; I hope its enough.  Adding a new affix file directive seems to be adding complexity that is not yet needed.

**Comment by ampli** [comment]
I first fixed it by adding an additional word  status "WS_INFIXMARK", which marks words which have an INFIX_MARK in them. I changed compute_chosen_words(), to combined only alternatives with so-marked words. The main benefit in adding this mark is that it solves the ambiguity caused by an input word that happens to have a character equal to INFIX_MARK attached to it. Unfortunately it makes it impossible to input prefixes/suffixes in the "linkparser>" prompt for tests.

I then realized that further changes are needed in order to handle w/ well: What if we have w/unknown-word? And what about a combination like "w/John's ..."? The suffix_split() function was designed to handle such things, but due to changes it cannot do it now. And for the combination of both: "w/unknown-word's", all is lost - an infrastructure which allows in general such unknown words, with nice results, is tricky (but needed for languages which support gluing of words).

I finally found a solution that seems better, without any C source modification:
**Just add w/ to LPUNC instead of PRE**.

This seems reasonable because the original idea to put contracted words in SUF (and then PRE) was so spell results which are contraction will work. But spell results don't return something like w/word (even so this could be a clever fix for w\word or w|word ...).

Regarding the WS_INFIXMARK fix which seems useful in principle, I think it is better not to add features just now to the tokenizer, beside the needed ones for the continues development of the library and the languages it supports, because the tokenizer needs a rewrite (I wrote about my FST plan in the group).

**Comment by linas** [comment]
Right!! I moved w/ to LPUNC  Don't know why I didn't think of that earlier.  General mental confusion, I guess.

I'm closing this issue, it all seems good now. Re infixes and FST .. yes. I have no clear vision for this at this time. Maybe later.
