### ISSUE TITLE
Disjunct strings sometimes have ZZZ in them.

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#241]
Even if ZZZ is not being used, it does show up sometmes in disjunct strings.

**Comment by ampli** [comment]
The new tokenizer is aggressive in creating alternatives, even for English, and when they contain different number of tokens, and empty word is automatically inserted,  a thing that can create a ZZZ link if the selected alternative is not the longest.
For example, there is now no special handling for let's, so the tokenizer emits both "**let's**" and "**let     's**".
Since only "**let's**" is selected, there is a ZZZ link involved:
```
    +---Wi--+--I--+Osm+
    |       |     |   |
LEFT-WALL let's do.v it 

            LEFT-WALL    0.000  Wi+ RW+ 
                let's    0.000  Wi- ZZZ+ I+ 
                 do.v    0.000  I- O+ 
                   it    0.000  Osm- 
           RIGHT-WALL    0.000  RW- 
```

Solution: When removing the ZZZ links, a code should be added to remove also the ZZZ connectors from the selected disjuncts.

**Comment by linas** [comment]
closing stale bug.

**Comment by ampli** [comment]
Double-quotes still use ZZZ. I have a plan to use null-links instead of ZZZ, and a preliminary but unfinished version that does it, but it needs some more thinking.
