### ISSUE TITLE
install?

### ISSUE THREAD

**Issue by edpell** [opencog/link-grammar#290]
As the README suggests ./configure but no such file exists can the README be updated to the current build, make, test, install method? Thanks.

**Comment by ross-nordstrom** [comment]
I had to run `autogen.sh` first - https://github.com/opencog/link-grammar/issues/289

**Comment by linas** [comment]
The README is tailored for users of the release tarball, which does include a configure file.

I recommend sticking to the release tarball in almost all cases; the contents of the git master branch are sometimes broken or under construction.   The tarball, at least, has passed unit tests.

**Comment by edpell** [comment]
I tried to get the tarball but verify failed. Should I run without verify?

ed@edlinux:~/link-grammar$  gpg --verify link-grammar-5.3.4.tar.gz.asc
gpg: directory `/home/ed/.gnupg' created
gpg: new configuration file `/home/ed/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/ed/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/ed/.gnupg/pubring.gpg' created
gpg: can't open `link-grammar-5.3.4.tar.gz.asc'
gpg: verify signatures failed: file open error


I also tried th autogen.sh no luck

ed@edlinux:~/link-grammar$ ./autogen.sh 
./autogen.sh: 14: ./autogen.sh: automake: not found
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
Creating aclocal.m4: aclocal  -I ac-helpers
automake --add-missing --copy --foreign

* * * warning: possible errors while running automake - check autogen.err

Creating configure...

* * * warning: possible errors while running automake - check autogen.err

./autogen.sh: 79: ./autogen.sh: ../configure: not found

Now type 'make' to compile link-grammar.

**Comment by linas** [comment]
The gpg messages suggest you've never used gpg before.  That means that I am almost surely not in your trust chain, and so the verify will fail.   In addition, the error message suggests that you did not download the cryptographic signature, anyway: it is the "asc" file.

The reason I recommended against using the autogen step is that I knew it would fail.  The use of autogen requires that assorted autotools be installed first.    The tarball distribution does not require the autotools to be installed.  Also, the tarball distribution never mentions autogen, which is why you should not be using it.

**Comment by edpell** [comment]
Tarball from http://www.abisource.com/projects/link-grammar/
link-grammar-5.3.4
has configure installing fine
