### ISSUE TITLE
Locale(?) warning on El Capitan

### ISSUE THREAD

**Issue by christian-storm** [opencog/link-grammar#293]
I was hoping someone could offer some help to figure out what is going awry with my link-grammar installation.

I receive the following repeated error when I run bindings/python-examples/tests.py or when I run link-grammar from the commandline:

$ link-parser 
link-grammar: Info: Dictionary found at /usr/local/share/link-grammar/en/4.0.dict
link-grammar: Warning: The word "?" found near line 9070 of en/4.0.dict matches the following words:
	?
	This word will be ignored.
link-grammar: Info: Using locale en_US.UTF-8.
link-grammar: Info: Dictionary version 5.3.4.

Similar warnings arise when I run tests.py leading to a segfault of python (2.7.10).

The warning is emitted at link-grammar/dict-file/read-dict.c:1568

I hope some of the following installation warnings help shed some light on what is going on.

  Installation:
==========
Mac OS 10.11.3 El Capitan
link-grammar-5.3.4.
**./configure --disable-java-bindings --enable-python-bindings --disable-editline**

Resulting in:
C compiler:    gcc  -DUSE_SAT_SOLVER=1 -DHAVE_SQLITE=1 -g -O2 -O3 -D_DEFAULT_SOURCE
C++ compiler:    g++  -DUSE_SAT_SOLVER=1 -DHAVE_SQLITE=1 -g -O2 -O3 -Wall -std=c++11 -stdlib=libc++

**make**

Results in the following warnings:
I receive numerous warnings for Solver.h lines 238, 239, 240, 242, and 243:
../../link-grammar/minisat/Solver.h:238: warning: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'uint64_t'
      (aka 'unsigned long long') [-Wformat]
    printf("restarts              : .%zu.\n", starts);

  CXXLD    libsat-solver.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libsat-solver.a(variables.o) has no symbols

fast-match.c:466:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"

  CCLD     liblink-grammar.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(histogram.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(spellcheck-aspell.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(spellcheck-hun.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(variables.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(histogram.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(spellcheck-aspell.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(spellcheck-hun.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/liblink-grammar.a(variables.o) has no symbols

Making all in python
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CXX      ../../bindings/python/_clinkgrammar_la-lg_python_wrap.lo
../../bindings/python/lg_python_wrap.cc:539:7: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
      register size_t l = 0;
....
There are many register warnings.

**sudo make install**

Besides some ranlib errors everything seems fine.

**Comment by linas** [comment]
Hi,

The build errors are all unfortunate but ignoreable.

The warning about ? is more serious.   It occurs because, somehow, on
MacOS, you are not actually in a UTF-8 locale  (even though the print
statement suggests that you are.)

All of the data files are in utf-8, and non-ASCII symbols are represented
using multiple bytes (typically 2 or 3).  Almost all of the code in the
link-parser uses just plain utf8, but there are a few corners where the
utf8 gets converted to multi-byte wide characters (wcs) and that conversion
is very locale dependent -- it uses the mbsrtowcs and the mbstate_t type
and wchar_t  -- and thus, a bad locale setting messes up everything.  It
would be best if we could eliminate this code ...

So, what is happening, for you, is that some conversion somewhere, is
messed up, resulting in two different utf-8 strings being mangled, probably
truncated.  They get mangled into the same form, and the code notices that
it has already seen that form, and prints an error.

Notable, in your case, is line 9070 which points at the currency file,
which, if you look at it, contains lots of wonky currency symbols in it.
They're getting mangled.

You have several options:
-- ignore the problem.  Text with utf8 characters may not parse correctly
-- fiddle with your locale settings. Not sure how that is done in MacOS
-- remove all uses of wchar_t from the link-parser code base. This is a
huge undertaking even for an experienced programmer.  But its probably the
right thing to do in the long run. The wide-character, locale-dependent
stuff is a recurring source of problems.

Linas

**Comment by christian-storm** [comment]
Thanks for the help Linas.

Well, after reading this I decided to try and pitch in and spent the day trying to figure out what is going on.  I made sure my shell was properly defining the locale environment variables:
`LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"`

I then instrumented the code to make sure the code was using the right locale before dictionary_six_str::insert_list.  I'm stumped because everything seems to have checked out.  

To 'fix it' I ended up commenting out the warning code and recompiling.  I was wondering if there is a bit of printf or strcmp code that I could add to read-dict.c that would help figure out what is going on?


The bigger issue seems to be with Russian.  Screenfuls of Warning messages and then a segfault.

link-grammar: Warning: The word ".=" found near line 417 of /ru/stem.dict matches the following words:
	.=
	This word will be ignored.
link-grammar: Warning: The word "аник.=" found near line 417 of /ru/stem.dict matches the following words:
	аник.=
	This word will be ignored.
link-grammar: Warning: The word "ар?" found near line 417 of /ru/stem.dict matches the following words:
	ар?
	This word will be ignored.

link-grammar: Info: Dictionary found at ./data/ru/4.0.dict
link-grammar: Error: Regex missing colon on line 103 of file ru/4.0.regex

Strange because the file seems fine around line 103.

I hope this helps.

**Comment by linas** [comment]
On Mon, Apr 25, 2016 at 6:22 PM, christian-storm <notifications@github.com>
wrote:

> Thanks for the help Linas.
>
> Well, after reading this I decided to try and pitch in and spent the day
> trying to figure out what is going on.
>

I'm sorry. There are relatively few MacOS users, and no regular MacOS
maintainer.

>
> LANG="en_US.UTF-8"
>
This looks reasonable; are you sure that all needed components for unicode
are installed?


> To 'fix it' I ended up commenting out the warning code and recompiling.
>

Heh. That only hides the problem.


> I was wondering if there is a bit of printf or strcmp code that I could
> add to read-dict.c that would help figure out what is going on?
>
Oof.  OK, lets focus on the currency file.  It's here:
https://github.com/opencog/link-grammar/blob/master/data/en/words/currency.p
 near the bottom is Złoty -- if you look at this file with  your editor,
does it look OK?  (notice the slash through the l)

The file itself is read in by this code:
https://github.com/opencog/link-grammar/blob/master/link-grammar/dict-file/word-file.c
 which reads one byte at a time, and looks for a space: see line 31:
 lg_isspace().

Perhaps getchar on MacOS truncates the byte, and returns only 7 bits,
instead of 8 ??

Perhaps lg_isspace() is broken. Its here:
https://github.com/opencog/link-grammar/blob/master/link-grammar/utilities.h#L156-L162

Placing a print here:
https://github.com/opencog/link-grammar/blob/master/link-grammar/dict-file/word-file.c#L48

should always print a valid word, even if it has utf8 chars in it.  If the
print is bad, then its a getchar/isspace problem. It its good, the problem
is somewhere else.


It will print vast amounts of stuff, try it with russian, it should all
look like valid cyrillic.

> The bigger issue seems to be with Russian. Screenfuls of Warning messages
> and then a segfault.
>

Yeah, no surprise. Russian has no ascii chars in it at all.

--linas

**Comment by christian-storm** [comment]
I'm a bit out of my depth here but I seemingly found two ways to fix the
problem.  UTF-8 handling is a dark art.

The change that made the most sense initially is something you allude to in
your comments
https://github.com/opencog/link-grammar/blob/master/link-parser/link-parser.c#L233-L234
.

If I change fgetc to fgetwc and change from char to wint_t in word-file.c
it solves the problem of loading the dictionaries. However, per your first
response it seems you want to move away from wchar_t.  However, it seems
like the code is a mix of char and wchar already.

The other fix, which was surprising to me, is to set to locale to native C.
To force this, I added locale = setlocale(LC_CTYPE, "C"); between line 717
and 718
https://github.com/opencog/link-grammar/blob/master/link-parser/link-parser.c#L717-L718.


The thing I don't quite get is that for the python examples to work I had
to remove the setlocale lines with both fixes, i.e.,
https://github.com/opencog/link-grammar/blob/master/bindings/python-examples/tests.py#L18
 and
https://github.com/opencog/link-grammar/blob/master/bindings/python-examples/example.py#L11
.

Hope this helps.

>

**Comment by linas** [comment]
OK, thanks.  I think I see what to do, and that is to also stop using
fgetc.  Its very hard to bite my tongue and not say "MacOS is just broken".
I get the impression that they just "think different" for no valid reason
at all.  Thus, the long-term plan is to not use anything at all that could
ever be locale dependent -- the concept of locales just appears to be too
broken across too many operating systems -- despite the efforts of the
standards bodies, the vendors have failed to adhere to the standards.

I will see if I can create a quick fix right now, and see what happens.

--linas

**Comment by linas** [comment]
OK, so here is my quick fix:

edit utilities.h and somewhere near the bottom, add this:

#if __APPLE__
static inline int lg_fgetc(FILE *stream)
{
   char c;
   size_t nr = fread(&c, 1, 1, stream);
   if (0 == nr) return EOF;
   return (int) c;
}
#endif

and then also edit word-file.c  and change the  (two) occurances of fgetc
to lg_fgetc

That should solve the dictionary load issues, without having to change the
locale.   It should get the python stuff to work, although the command-line
too needs more work for russian.

Can you confirm that this is enough? If so, I will publish a new version of
LG maybe later today.

**Comment by linas** [comment]
I am hoping that pull request #294 fixes this issue. Now, building from git is hard, so you don't have to test that; however, the above-mentioned lg_fgetc routine should be enough to confirm the fix.

**Comment by christian-storm** [comment]
Apologies for the delay Linas.  I've confirmed the fix.  As you noted
tests.py and example.py both segfault python when processing Russian.
Sorry to have bothered you with this but I'm very appreciative of your
attentiveness.  It looks like I have a happy Mac OS X link-parser again!

**Comment by linas** [comment]
I just published version 5.3.5 which incorporates this fix.

http://www.abisource.com/downloads/link-grammar/5.3.5/link-grammar-5.3.5.tar.gz

I just re-read your notes: with the fix that I provided, do the russian python files still fail? Or do they now work?  If they fail, could you retest with version 5.3.5 ?

**Comment by christian-storm** [comment]
I happy to report this new version fixes Russian.  However, when I run
tests.py I get the following error output.

I searched the tar ball (find . -name parses-quotes-en.txt) and didn't see
this file.  I did see parses-en.txt.  I didn't install
spell checking so that may account for the other error.

.link-grammar: Info: Dictionary found at
/usr/local/share/link-grammar/ru/4.0.dict

.

======================================================================

ERROR: test_quotes (__main__.ZENLangTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "./tests.py", line 439, in test_quotes

    linkage_testfile(self, self.d, self.po, 'quotes')

  File "./tests.py", line 548, in linkage_testfile

    parses = open(clg.test_data_srcdir + "parses-" + desc +
clg.dictionary_get_lang(dict._obj) + ".txt")

IOError: [Errno 2] No such file or directory: 'parses-quotes-en.txt'




======================================================================

FAIL: test_d_spell_guessing_on (__main__.HEnglishLinkageTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "./tests.py", line 297, in test_d_spell_guessing_on

    ['LEFT-WALL', 'I.p', 'love.v', 'going.v', 'to.r', 'shop[~].v', '.',
'RIGHT-WALL'])

AssertionError: Lists differ: ['LEFT-WALL', 'I.p', 'love.v',... !=
['LEFT-WALL', 'I.p', 'love.v',...


First differing element 5:

shoop[?].v

shop[~].v


  ['LEFT-WALL',

   'I.p',

   'love.v',

   'going.v',

   'to.r',

-  'shoop[?].v',

?      -  ^


+  'shop[~].v',

?        ^


   '.',

   'RIGHT-WALL']


----------------------------------------------------------------------

Ran 53 tests in 13.893s


FAILED (failures=1, errors=1)

**Comment by linas** [comment]
Yes, we forgot to include that file; it doesn't seem worth the effort to spin a version 5.3.6 just to pick it up. 

The spell-guessing errors also seem to be ignorable.  I'm closing this issue as "fixed": if anything else comes up, please open a new bug report.

(Also, let me/the mailing list know how your experiments progress; its always interesting to see what users do with this thing.)

**Comment by christian-storm** [comment]
Will do.  Thanks for your help Linas!  I owe you a beer or coffee next time
I'm down in Austin.
