### ISSUE TITLE
make dist doesn't work

### ISSUE THREAD

**Issue by jbicha** [opencog/link-grammar#319]
Ubuntu 16.10 (development). I think I have all the right build dependencies installed.

I tried running make dist to make my own tarball for testing. [Build log attached](https://github.com/opencog/link-grammar/files/340436/link-grammar-make-dist.txt).

```
$ ./autogen.sh
$ ./configure --enable-perl-bindings
..
make[3]: Entering directory '/home/jeremy/devel/github/link-grammar/bindings/perl'
make[3]: *** No rule to make target '../../bindings/perl/clinkgrammar.pm', needed by 'distdir'.  Stop.
make[3]: Leaving directory '/home/jeremy/devel/github/link-grammar/bindings/perl'
```

**Comment by linas** [comment]
I can reproduce this easily. I've never tried to say `make dist` before saying `make`    The make-all step runs swig to create the `clinkgrammar.pm` and `py` files which are included as a part of dist.  It was done this way, so that users would not need to install swig and any fiddly bits that swig may require.

**Comment by linas** [comment]
pull re #320 should fix this for you.

**Comment by jbicha** [comment]
Yes, it works now. Thank you!
