### ISSUE TITLE
The argument of isupper/islower etc. needs to be converted to unsigned char 

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#347]
From the manual:
**These functions check whether c, which must have the value of an unsigned char or EOF, falls into a certain character class according  to the specified locale.**

However, in the library code the coding is always of this style:
`isupper((int)*s)` or `isupper(*s)`
when `s` is defined as 'char *s`.

The problem is that isuppe() etc. are not defined for negative values (beside EOF).
If char is signed (a usual thing) and a character happens to be with 8-th bit set (e.g. part of a utf-8 character or from the upper half of 8859-x, or a hard-space), an undefined result may happen (unexpected true value, or even a crash).

This may explain the following comment in utilities.h:
**/\* MSVC isspace asserts in debug mode, and mingw sometime returns true,
     \* when passed utf8. Thus, limit to 7 bits for windows. */**

See:
[do-i-need-to-cast-to-unsigned-char-before-calling-toupper](http://stackoverflow.com/questions/21805674)
[Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char](https://www.securecoding.cert.org/confluence/display/c/STR37-C.+Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char)

There are a lot of places to fix, and I would like to send a pull request. I would like to do it as a separate patch, so I will be to send it only after sending the per-dictionary-locale pull request, due to conflicts.

**Comment by linas** [comment]
Well, this is used ONLY for the link-types, and the rules have been, until now, that "link types must be ASCII" -- i.e. must be 7-bit clean.  Now, you could change the code to allow utf8 link types, but this will have a direct effect on parse performance -- there's lots of upper/lower-case string compares, and wild-card, etc going on.  Its a significant part of the overall CPU cycles spent on parsing.

Now, if I recall correctly, you added a mechanism to cache the upper-case part of a string, so that upper-case connectors compare quickly?   In this case, allowing utf8 in the upper-case part of the string won't affect performance. It will still affect the lower-case part, but maybe not so much...

**Comment by ampli** [comment]
There are several issues here.
1. Sometimes the current code uses UTF-8-aware code to compare stuff from the dictionary.
See `utf8_upper_match()` in [constituents.c](https://github.com/opencog/link-grammar/blob/59545d5a6807bb5653e942723a28e3c402ff518c/link-grammar/constituents.c#L67) and  [idiom.c](https://github.com/opencog/link-grammar/blob/59545d5a6807bb5653e942723a28e3c402ff518c/link-grammar/idiom.c#L72) .

In the per-dict-locale change, I had to change these places to use plain ASCII comparisons, because there is no point to go all the way to provide these functions the dictionary locale, and anyway, the the idiom subscripts are created with ASCII numbers on the first place. Also doing potentially locale-depended comparisons seems to me somehow wrong.

Regarding the potential problem with negative characters:
1. Bad characters can get to the dictionary by mistake, and we don't want the program just to crash.
2. `isspace()` is used directly on dictionary bytes. If there is a prior check for negative values, I missed it.
3. The fix is easy in all the cases: there is just a need to cast the argument to `unsigned int`. So I think it could be a good idea to implement that.

Regarding overhead in connector comparison, in any case I would like to implement my idea of connector enumeration, which will allow fast comparisons (comparing 2 numbers + mask) disregarding the connector content.

**Comment by linas** [comment]
ah, I thought you already did the connector enumeration code. I guess not. It was a good idea.

Casting to an unsigned int will not fix anything at all.  If you have a signed char that is -1, then its 0x80 and casting it to an unsigned char will turn it into 0x80=128  which will still crash any code that fails to deal with the sign bit. If you cast the signed char to unsigned int, it will get sign-extended first, into 0xffffff80 which is -127, so whatever crashes will still crash.  The only way to be 7-bit clean is to mask with 0x7f and then it doesn't matter if its signed, unsigned, char or int.

**Comment by linas** [comment]
I've seen and fixed multiple casting errors in assorted code, over the decades -- casts have a way of not working the way you might think they should work, and are a frequent source of programmer error.  They're just dangerous - playing with fire.

**Comment by ampli** [comment]
In the standard parsing there is already a cache for the uppercase part. But a full connector-matching is still done in other places (like pruning and the SAT parser). Fast comparison for the lowercase part can also be implemented.

Regarding casts:
Note that the `is*()` functions are **guaranteed** to work, by their definition, with a cast to unsigned char of any char value. So, for example, `isupepr(c)`, when `c` is 0x80, may malfunction, while `isupper((unsigned char)c)` is always **guranteed* to work fine!

So custing to unsigned char is indeed the proper solution here,  and is guaranteed (by definition and design) to work fine.  In this particular case, it is the only recommended practice. Please see the links that I included above.

**Comment by linas** [comment]
when I type in `man isupper`, I get this:
```
ISALPHA(3)                       Linux Programmer's Manual                       ISALPHA(3)

NAME
       isalnum,  isalpha,  isascii,  isblank,  iscntrl, isdigit, isgraph, islower, isprint,
       ispunct, isspace, isupper, isxdigit - character classification routines

SYNOPSIS
       #include <ctype.h>

       int isalnum(int c);
       int isalpha(int c);
       int isascii(int c);
       int isblank(int c);
       int iscntrl(int c);
       int isdigit(int c);
       int isgraph(int c);
       int islower(int c);
       int isprint(int c);
       int ispunct(int c);
       int isspace(int c);
       int isupper(int c);
```
i.e. a signed int. If you pass in an unsigned char 0x80 on Linux, it will get signed-extended to 0xffffff80, on linux. Yes, I suppose if you accidentally pas i the signed int 0x00000080 instead, it might malfunction.

The problem is that  it is very easy to mis-understand what the compiler is doing, and accidentally passing 0x00000080  instead of 0xffffff80, (or vice-versa) ... this is where casting bugs always show up -- misunderstanding what the compiler actually did with the cast.

**Comment by ampli** [comment]
Please reconsider...

If you look several lines down in the same manual you quoted from, you will find:

--
...
**DESCRIPTION**
       These functions check whether c, which must **have the value of an unsigned char** or
       EOF, falls into a certain character class according to the specified locale.
...

--

[Emphasis added.]

So these functions must never get a negative int argument, including anything which is promoted to negative int (but EOF)!

```
/* This is  **wrong** on architectures in which char is signed (the x86/x64).  */
char c = 0x80;
if (isspace(c)) ...

/* This is also wrong from the same reason. The (int) cast just does nothing  */
 * at all, as the argument is promoted to int anyway. */
if (isspace((int)c)) ...
```
as the 0x80 will get sign extended to a negative integer (and isspace() and the like is defined only for positive values < 255 and EOF).

> if you accidentally pass in the signed int 0x00000080 instead

I don't understand you - 0x00000080 is positive and < 256, so it is a totally fine argument to isspace() no problem will happen...

On the other hand, the following ensures that the function will never malfunction:
```
char c = ANYTHING;
if (isspace((unsigned char)c) ...
```
as `(unsigned char)c` is guaranteed to be positive and < 255.

(I neglected the EOF issue because it is not relevant to this particular discussion.)

**Comment by linas** [comment]
I'm not saying anything complicated.  I'm just saying that, if you made a poll of some random C programmers, and asked them wheat happens when you pass an char to a function taking int, about half of them will get it wrong.  Sign extension is just something that even smart programmers get incorrect, when they're tired and hungry. 

As to the words "must have the value of an unsigned char", I don't even know what those words mean.  Its impossible for a signed int to have any value that is not a signed int, so that phrase is non-sense, written by someone who (obviously) did not understand how sign extension works, or maybe was sleepy, tired, or hungry when they wrote that.

**Comment by linas** [comment]
Let me put it another way: it you want to make this work correctly, cast it to an int first, and then mask it with 0x000000ff  -- that way, you will always pass a value between 0 and 255, no matter how the sign-extension is done.

**Comment by linas** [comment]
0r just mask it with 0x7f at any time. That way you are 7-bit clean, and the sign bit is never an issue.

**Comment by ampli** [comment]
>As to the words "must have the value of an unsigned char"
...
Its impossible for a signed int to have any value that is not a signed int

Please note: It says "of an unsigned **char**", NOT "**of an unsigned int"!

A "value of an unsigned char" (this is what it says) is a value which is positive and is less than 256.
There is nothing which is nonsense here.

It means isspace() etc. should not get a value out of the range 0 to 255 (and EOF which is -1 which is specifically allowed too). Regarding C programmers, anyone should know that signed char is promoted to signed it for functions with it argument.

Supposing CERT is not among ones that don't know how sign extension works, here is what they say in the link I provided above (I quote the relevant parts):

## STR37-C. Arguments to character-handling functions must be representable as an unsigned char
...
**Noncompliant Code Example**
```
const char *t = s;
...
while (isspace(*t) && (t - s < length)) {
...
```
**Compliant Solution**
```
  const char *t = s;
...
  while (isspace((unsigned char)*t) && (t - s < length)) {
...
```

**Comment by ampli** [comment]
>0r just mask it with 0x7f at any time. That way you are 7-bit clean, and the sign bit is never an issue.

Masking with 0x7f will also solve the issue, becasue then the value will be subset of that "of an unsigned char" (0...127), which is of course fine by definition.

However, casting to (unsigned char) is more efficient (no additional assembly instruction is needed),
and is according to the manual and the documented best practice.

**Comment by linas** [comment]
OK, I don't care that much. The "documented best practice" is clearly wrong. I have fixed casting bugs in the Linux kernel, in the gcc compiler, and in NFS, and all I can say is what I already said: whenever C developers write code that casts between signed and unsigned, there is a 50% chance that they'll do it exactly wrong.

As to efficiency, I believe that both gcc and llvm/clang are able to correctly combine masks and casts to create optimal code, (for powerpc, the s390, and the hexagon instruction set ; I have never used x86).  at least for & 0x8f  but &0x7f may require two insns.  Compilers are good at optimizing bitops, mostly because they are relatively easy to optimize.
