### ISSUE TITLE
Python bindings: num_linkages_found etc.

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#398]
Currently we have these Sentence methods:
```
num_linkages_found()
num_valid_linkages()
num_linkages_post_processed()
```
However, in the Python bindings the linkages are an object returned by the sentence_parse() method of Sentence, which has a `next` method to get the next linkage, and recently I added to it a __len__ method so `len(Linkages)` actually gives  sentence_num_linkages_found().

I think that it can be more "Pytonish" to implement the above listed functions also (or maybe only) in that way, i.e. to add to the said **Linkages** object (the one that is returned by `sentence_parse()`) also the above-mentioned **num_*()** methods.

Is it a good idea?

**Comment by linas** [comment]
The default for len should probably be num_valid_linkages() instead of num_linkages_found() -- this is, because, in the normal case, only the valid linkages are ever returned.

The only time that one is interested in num_linkages_found() is when one is trying to view the "bad" linkages, typically while debugging the dictionary.   I do not know of any other valid, reasonable uses for this -- I cannot imagine how any user would ever want to get the bad linkages using the python bindings. 

Thus, I'm thinking that adding these extra methods to python is a bad idea -- it just makes the API bigger, more complicated, harder to understand.  (Even I have trouble remembering the difference between these three)  Any API that is big and hard-to-understand is likely to be mis-used, leading to bugs, complaints, general dissatisfaction.  And general dissatisfaction is very, very bad -- it is very hard to fix.

So, no don't add these to the api. Do replace len by "num valid linkages", though.

**Comment by ampli** [comment]
> The default for len should probably be num_valid_linkages()

Indeed it was rather incorrect. I just sent a PR for that.

> I'm thinking that adding these extra methods to python is a bad idea

They are currently used in example.py. Do you mean it is better to use there the corresponding direct C bindings **instead**? (They are also used in my yet-unpublished link-parser rewrite in Python.)

> (Even I have trouble remembering the difference between these three)

Me too. I had an error in example.py regarding the report of random sampling.
I just sent a fix. It can be verified by uncommenting this line in the new example.py:
```
#po.linkage_limit = 3
```

Back to my issue point:
It was whether to leave the binding as (for example) "sent.num_linkages_found(),
or make a new binding linkages.num_found() (when linkages is the object returned from sent.parse()) , which seems more logical. However, it may be increase to confusement around these terms (and not needed if the bindings are deleted).

**Comment by linas** [comment]
Ugh.   I'm thinking that simply removing 
```
    def num_linkages_found(self):
        return clg.sentence_num_linkages_found(self._obj)

    def num_linkages_post_processed(self):
        return clg.sentence_num_linkages_post_processed(self._obj)
```
from the python bindings would be best, and renaming `num_valid_linkages` to `num_linkages`

Yes, that's not backwards compatible, but I'd rather squash this earlier, than later.

**Comment by ampli** [comment]
No problem to remove num_linkages_found()/num_linkages_post_processed() (a PR will follow).

>renaming num_valid_linkages to num_linkages

I suggest to remove also num_valid_linkages (i.e. not replace it by num_linkages).
Instead I propose the following
```
sent = Sentence(text, lgdict, po)
linkages = sent.parse()
print('Found {} linkages'.format(len(linkages)))
```
i.e. I propose to use len(linkages) instead of sent.num_linkages(), like the recently introduced len(sent) for what could be implemented by sent.length(). This is in the Python tradition to define length of objects by len(object).

**Comment by linas** [comment]
yes OK
