### ISSUE TITLE
Windows: Eliminating the need for using a regex library

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#401]
I would like to add to **regex_morph.c** conditionally compiled code for using C++ regex.
This way, a major obstacle of properly installing a regex library for windows LG library compilation, will be avoided.

This fix can be stand-alone (i.e. only for the Windows build, which will define, for example, USE_CPPREGEX), or can be provided also through `configure`, with, for example, `--with-c++-regex`.

**Comment by linas** [comment]
Huh. I assume you mean this: http://www.cplusplus.com/reference/regex/

Does windows actually support that? I got the impression that their compilers and libraries tend to be 5-10 years behind the times, for standard support. (Apparently, they're slow to support standards on purpose, this is a competitive lock-in ploy. For me, this came out during a hot debate with the MS reps on a standard committee I once sat on. They said "our customers like it that way, that's why they pick us.".).

**Comment by linas** [comment]
I mean,  if Windows actually supports this, and it does everything we need, then we can simplify the code base, and just use it across-the-board, and not use the pcre or gnu regex libraries at all.  I mean regex is 40 or more years old, now, welcome to the modern era, Microsoft?

**Comment by ampli** [comment]
> Huh. I assume you mean this: http://www.cplusplus.com/reference/regex/

Yes.
>Does windows actually support that?

Their current C/C++ compiler (MSVC14) has almost full support of C99, including regex.
(A noteable thing which is yet not supported is C VLA.)

> I mean, if Windows actually supports this, and it does everything we need, then we can simplify the code base, and just use it across-the-board, and not use the pcre or gnu regex libraries at all. I mean regex is 40 or more years old, now, welcome to the modern era, Microsoft?

There are reports that some implementations of the C++ standard library has slow regex, so I thought that it could be a good idea not to discard the POSIX regex support yet.

But if on Linux C++ regex are comparable fast (can be tested), it may be enough for us to drop POSIX regex support. altogether.

Just tell me what to do and I will send a PR :)

**Comment by linas** [comment]
If the Linux C++ regex are comparably fast, (and also do everything we need) then we should drop POSIX. If you want to be a perfectionist, then also test OSX+clang.

**Comment by linas** [comment]
The discussion here:
http://stackoverflow.com/questions/20942450/why-c11-regex-libc-implementation-is-so-slow
and here
http://stackoverflow.com/questions/33163365/regex-works-very-slow
suggests that the clang implementation is broken.  Since OSX uses clang by default, this would hurt all Apple users. So perhaps staying on POSIX is a good idea until clang is fixed?

(I am assuming that gnucc did the right thing)

**Comment by ampli** [comment]
> The discussion here:
> http://stackoverflow.com/questions/20942450/why-c11-regex-libc-implementation-is-so-slow
> and here
> http://stackoverflow.com/questions/33163365/regex-works-very-slow

Indeed these messages are alarming. The last one is from one year ago, so it will take time until fixes, if done,  will propagate to main distributions. (I don't know when Microsoft will make a fix, but according to my experience it may take years...). So I will close this issue and will reopen it if my tests show that its performance is like POSIX regex on Linux, Mac and Windows.
