### ISSUE TITLE
crash or overflow in splitter

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#496]
The following "sentence" causes the "ady" splitter to silently chew through about 1/2 hour of CPU time, and then spit out error messages. This is with all-default settings, the standard command-line client only.

```
- |3-1|25-23|20-25|25-17|25-11||95-76|couleur=gris}} - |3-0|28-26|25-19|25-23|||78-68}} - |3-1|25-21|25-21|13-25|25-12||88-79|couleur=gris}} - |3-1|21-25|33-31|40537|25-15||104-83}} - |3-2|25-23|22-25|25-22|17-25|17-15|106-110|couleur=gris}} - |3-0|25-19|25-13|25-23|||75-55}}
```

The errors are:
```
link-grammar: Error: Word } reached 10 splits. It will not get split further. The result is undefined.
Run with !verbosity=6 to debug
link-grammar: Error: Word } reached 10 splits. It will not get split further. The result is undefined.
Run with !verbosity=6 to debug
link-grammar: Error: Word } reached 10 splits. It will not get split further. The result is undefined.
```

**Comment by linas** [comment]
This gives an outright, immediate crash:
```
ISBN 0-380-72001-9.  http://books.google.be/books?id=FMsNAG-gresC&pg=PA144&lpg=PA144&dq=vlakfontein+Dixon+kemp&source=web&ots=8cB7anqlpV&sig=REOVNA8sQO8iTZhI-0_IHVdhySQ&hl=en&sa=X&oi=book_result&resnum=3&ct=result.
```

**Comment by ampli** [comment]
I will look at both and will send a PR to fix them.

**Comment by ampli** [comment]
This definition exists in anysplit.c:
`split_cache scl[MAX_WORD];`

Since now the input word size is dynamic in all/most of the places and is not enforced any more in seprate_word(), an overflow happen.

However, I think there is no point to random-split such big words (even if they are in utf-8 with 4-bytes per codepoint), and in any case it will cause a big overhead to do so, I propose to make a limit on the word size that get splits in anysplit, and leave such big words unsplit. (I Also think there is no point to make this array dynamic and resize it.)

For example, maybe 32 codepoints is a reasonable limitation.
Unless you have a better idea, I will define a constant MAX_WORD_TO_SPLIT for that.

**Comment by linas** [comment]
A max size is fine, I guess.

**Comment by linas** [comment]
wow thanks, that was fast!
