### ISSUE TITLE
configure fails

### ISSUE THREAD

**Issue by yurivict** [opencog/link-grammar#520]
```
$ ./autogen.sh
...
checking for locale_t in locale.h... yes
../configure: 17244: Syntax error: word unexpected (expecting ")")
```

This section in configure script causes the problem:
```
if test "x$enable_TLS" == xyes
then
                        AX_TLS(,:)
        test "$ac_cv_tls" != "none" && error_handler_per_thread=yes
fi
```

FreeBSD 11

**Comment by linas** [comment]
well, the AX_TLS is a mcaro, and should have been replaced in the configure script.  My guess is that you need to install the "autoconf  archive"   https://www.gnu.org/software/autoconf-archive/ax_tls.html and try again. 

difficulties/irrations with autoconf and autotools is why I recommend that most people use the pre-pacakaged tarballs, instead of working from the git repo. The tarballs are tested and known-good; the git repo sometimes contains broken stuff.

**Comment by linas** [comment]
https://www.gnu.org/software/autoconf-archive/index.htm

**Comment by linas** [comment]
current version is this:  http://www.abisource.com/downloads/link-grammar/5.3.15/link-grammar-5.3.15.tar.gz

Note to self: we should add the stuff about atutocnonf-archive etc. to readme and ALSO point at the latest taball!

**Comment by yurivict** [comment]
Thanks Linas!
autoconf-archive helped.

**Comment by ampli** [comment]
> Note to self: we should add the stuff about atutocnonf-archive etc. to readme and ALSO point at the latest taball!

I have just sent PR #526 that adds that.
