### ISSUE TITLE
installation is very tough

### ISSUE THREAD

**Issue by harishdamera** [opencog/link-grammar#589]
Am using python3 on Mac. 

Can someone please help me in installing link-grammar. Am struggling to do this installation since 48hours.

**Comment by linas** [comment]
what did you try and what were the errors?

**Comment by harishdamera** [comment]
brew install link-grammar
pip install pylinkgrammar

Error:
error: command 'gcc' failed with exit status 1 
error: command 'clang' failed with exit status 1

**Comment by linas** [comment]
I've never heard of `brew`.  Also, do NOT install pylinkgrammar, it is obsolete and unmaintained.  Use the python bindings that comes with the base link-grammar system. 

`gcc` and `clang` are compilers. Developers would need to install one or the other, and a whole bunch of other development tools first.   

Since you are not a developer, you have three choices:
1) try to find a binary distribution of link-grammar for MacOS, which has everything pre-built in it.
2) Get a friend who is a developer to compile it for you.
3) Download the 5.4.0 tarball, unpack it, and carefully read the README file, and follow the long and complicated instructions in there.

**Comment by ampli** [comment]
I tried installing link-grammar on an up-to-date MAcOS (Siera with latest updates).
I guess you also did most of these steps, but here are all of them for the record.

1) `brew install link-grammar`
It failed (exit 1 ...) but with clear and instructive error messages on what to do.
Here are the steps, as instructed in these messages (your mileage may vary - just follow the instructions you get):
```
brew cask install java
brew install link-grammar
brew link link-grammar
brew link --overwrite link-grammar
```

2) The I tried using clinkgrammar with python3, but it failed:
```
[mac:~]  python3
Python 3.6.0 (default, Dec 24 2016, 08:01:42) 
...
>>> import clinkgrammar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'clinkgrammar'
>>> 

[mac:~]  ls -d /usr/local/lib/python3*/site-packages/linkgrammar
/usr/local/lib/python3.5/site-packages/linkgrammar
```

3) It turns out the python version used by the current homebrew link-grammar is **3.5**.
So you need to switch to this version:
```
[mac:~]  brew switch python3 x
Error: python3 does not have a version "x" in the Cellar.
Versions available: 3.5.2_3, 3.6.0
Exit 3

[mac:~]  brew switch python3 3.5.2_3
Cleaning /usr/local/Cellar/python3/3.5.2_3
Cleaning /usr/local/Cellar/python3/3.6.0
23 links created for /usr/local/Cellar/python3/3.5.2_3
```

And now it works:
```
[mac:~]  python3
Python 3.5.2 (default, Oct 11 2016, 04:59:56) 
...
>>> from linkgrammar import *
>>> print(Sentence("This is a test",Dictionary(),ParseOptions()).parse().next().diagram())

    +----->WV----->+---Ost--+
    +---Wd---+-Ss*b+  +Ds**c+
    |        |     |  |     |
LEFT-WALL this.p is.v a  test.n 
```

**Comment by linas** [comment]
@ampli should we be installing python3 to dist-packages instead of site-packages?  There seem to be rules about this, and it also seems that many packages do not follow these rules.

**Comment by ampli** [comment]
@linas See [Python3 modules are not installed in the right path](https://bugs.launchpad.net/ubuntu/+source/automake/+bug/1250877).
Especially see the suggestion at the end of message #2 there.

There may be also other situations (that I still investigate if they can be handled automatically) as a private installation of python in the user's directory  (like what [pyenv](https://github.com/pyenv/pyenv) does), or availability of python under /opt (which is not a general installation prefix).  The LG package is currently installed in that case in a system directory, while the proper place seems the package directory of the said "private" python.

So I think it could be a good idea to add a `configure` directives for the python package directory.
Something like `--with-python-pkgdir=PKGDIR` and `--with-python3-pkgdir=PKGDIR`.
This way OS (e.g. Debian/Ubuntu) package maintainers will be able to configure the python package directory which is appropriate for their OS, if it turns out not to be what autoconf provides.

**Comment by linas** [comment]
Hmm. OK. That explains a lot. site-packages is indeed correct in principle, and Debian has altered it in practice.

I wouldn't add  `--with-python-pkgdir=PKGDIR` and `--with-python3-pkgdir=PKGDIR`; those are flags that automake itself should provide, not us.  It seems very unlikely that any OS packagers would discover and user our custom-built override options....
