### ISSUE TITLE
link-grammar: Error: While parsing dictionary...

### ISSUE THREAD

**Issue by alexei-gl** [opencog/link-grammar#735]
Some errors happening from time to time with bad repeatability: ```link-grammar: Error: While parsing dictionary /home/alex/data/dict/poc-english_9C_2018-04-07_0007/4.0.dict:
I expected a word but didn't get it.
	 Line 44, next tokens: ";" "�U"``` Repeatability is much higher when running in Anaconda virtual environment. Line number returned is usually the last line of a dictionary file. The problem has shown up when processing multiple data files with several dictionaries. The link-grammar library is called from python script using LG API. Link Grammar version is 5.4.4 built from official tar ball. Python version is 3.6.4 shipped with Anaconda. The error is happening once out of twenty times without virtual environment and aproximately once in five times in virtual environment. The garbage in double quotes is usualy different each time the error is shown up.

**Comment by linas** [comment]
Can you provide the dictionary which illustrates this problem?

Guesses include: 
-- Dictionary is not actually in UTF-8 format; this would explain why there are garbage bytes.
-- parser threads are launched before the read of the dictionary is finished. (There is currently no automatic mechanism to prevent this)  This seems unlikely, since python is single-threaded.  However, since you say "with several dictionaries", this might indeed be the problem.

**Comment by alexei-gl** [comment]
[dict.tar.gz](https://github.com/opencog/link-grammar/files/1894355/dict.tar.gz)
The script is running in one thread (I am not sure if LG implicitly creates another threads or not). It takes a dictionary file, makes dictionary folder, put .dict file in there, adding the rest three files and then parse input corpus files using the dictionary, then takes another dictionary file and do the same for it etc.

**Comment by ampli** [comment]
This is an old bug, from version 4.
I will send a PR soon.

**Comment by linas** [comment]
closing; fix has been merged, and new version will be published shortly
