### ISSUE TITLE
Python 3 binding:  Need step by step instructions for installations

### ISSUE THREAD

**Issue by vikram-nandan** [opencog/link-grammar#791]
Can someone provide me the step by step instructions for installation of link-grammar in Python 3? Also please suggest the best way to check the correctness of a sentence.

**Comment by ampli** [comment]
Which OS and version (e.g. Ubuntu 18.04, MacOS, Windows) do you use?

**Comment by vikram-nandan** [comment]
Thanks for the response, 

I myself had never tested it on Windows with anaconda (**only with "regular" Python2/3 distributions).**

Seems like you have worked with regular python 3 distribution in windows. can you please share those installation details? I guess i can make use of it.

**Comment by ampli** [comment]
The Windows compilation step by step instructions are in [msvc14/README.md](https://github.com/opencog/link-grammar/blob/master/msvc14/README.md).
You can also find this unofficial instructions that someone sent as an answer to [StackOverflow](https://stackoverflow.com/questions/38545726/how-to-use-the-link-grammar-parser-as-a-grammar-checker/40243925#40243925) (he said "32-bit" but the mostly apply to 64-bit, which is much preferred).

Both descriptions of how to build LG under Windows suppose you know how to use the relevant Windows tools for that purpose (explaining how to use them is out of scope of these descriptions).

I forgot to mention the option of using MSYS2 to compile LG on Window (you can then use the result directly on a Windows console).
The needed steps are very similar to compiling under Linux (you need to know some Linux or the like in order to do that). The step by step instructions are in [mingw/README-MSYS2.md](https://github.com/opencog/link-grammar/blob/master/mingw/README-MSYS2.md).
**However**, when I tried this on MSYS2 version 20161025, the Python3 binding failed (the Python2 bindings succeeded), due to apparent bug in the then MSYS2 Python3 package. Now that MSYS2 is at version 20180531, things are most probably better, but I didn't test it.

**Comment by linas** [comment]
Closing, I assume that the issues here are resolved.
