### ISSUE TITLE
python unit tests are failing for spell-check

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#800]
running `tests.py` generates an error:
```
AssertionError: 
'LEFT-WALL(0, 0) the(0, 3) seasonal[~].a(4, 11) lakes.n(12, 17) are.v(18, 21) hot.a(22, 25) RIGHT-WALL(25, 25)\nLEFT-WALL(0, 0) the(0, 3) seasonal[~].a(4, 11) lakes.n(12, 17) are.v(18, 21) hot.a(22, 25) RIGHT-WALL(25, 25)\n'
!= 
'LEFT-WALL(0, 0) the(0, 3) seas[&].n(4, 8) and[&].j-n(8, 11) lakes.n(12, 17) are.v(18, 21) hot.a(22, 25) RIGHT-WALL(25, 25)\nLEFT-WALL(0, 0) the(0, 3) seas[&].n(4, 8) and[&].j-n(8, 11) lakes.n(12, 17) are.v(18, 21) hot.a(22, 25) RIGHT-WALL(25, 25)\n'
: at ./parses-pos-spell-en.txt:12
```
which is confirmed at the command line:
```
linkparser> the seasand lakes are hot
Found 50 linkages (50 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=11)

    +--------------->WV-------------->+
    +----------->Wd------------+      |
    |      +--------Dmc--------+      |
    |      |        +-----A----+--Spx-+--Pa-+
    |      |        |          |      |     |
LEFT-WALL the seasonal[~].a lakes.n are.v hot.a

Press RETURN for the next linkage.
linkparser> 
	Linkage 2, cost vector = (UNUSED=0 DIS= 0.00 LEN=13)

    +------------------>WV------------------>+
    +---------->Wd-----------+------Spx------+
    |      +--Dmc-+---SJlp---+--SJrp--+      +--Pa-+
    |      |      |          |        |      |     |
LEFT-WALL the seas[&].n and[&].j-n lakes.n are.v hot.a

Press RETURN for the next linkage.
linkparser> 

	Linkage 3, cost vector = (UNUSED=0 DIS= 0.10 LEN=11)

    +-------------->WV------------->+
    +---------->Wd-----------+      |
    |      +-------Dmc-------+      |
    |      |       +----AN---+--Spx-+--Pa-+
    |      |       |         |      |     |
LEFT-WALL the sand[~].n-u lakes.n are.v hot.a

Press RETURN for the next linkage.
linkparser>
```

The above does not match the contents of `parses-pos-spell-en.txt`

**Comment by linas** [comment]
fixed by #801 - fix was to test only the first possible form

**Comment by ampli** [comment]
It's somewhat more complicated...

Spell guessing is done in two ways:
1. Suggesting "similar" words. The spelling library can offer a large number of such suggestions.
The `spell_guess` parse option controls how many such suggestions are considered. `spell_guess=0`means no spell guessing at all.
2. Suggesting word splits into two (or rarely more) words that their concatenation is **exactly** the original word. Naturally, the number of such suggestions is very limited. `spell_guess>0`  enables any number of such suggestions.

The problematic test checks the word position correctness when the unknown word `seasand` splits into `sea sand` and `seas and`. The single-word suggestions are unwanted in that case! If they get before any of the desired linkages (those with the word split), the test breaks. The original test code used `spell_guess==10`, which **aspell** just happened to suggest a single-word **seasonal** that formed a linkage with the lower metric.
However, it was not the first one it suggested, so limiting the number of single-word guesses to 1 avoided the problem. Regretfully there is currently no way to limit the number single-word guesses to **0** because this would prevent spell guessing altogether, and we would like to check here the multiple-word guesses.

So this solution works "by chance" - it can break by spell library or dictionary changes. In the pull-request comment I described a more robust and general solution which I actually implemented (selecting linkages by a regex filter), which I didn't include because its adds some complexity and was not actually needed even for solving this single (for now) problem.

**Comment by linas** [comment]
Thanks.  Re: the more complex fix: maybe there's a simple one: Check to see if any of the results are in the pool of acceptable results, ignoring the ranking, the order in which they appear.

Yes, keeping it simple is best; this is a unit test to make sure that a new release can be published, without obvious breakages in it...

**Comment by ampli** [comment]
> Check to see if any of the results are in the pool of acceptable results, ignoring the ranking, the order in which they appear.

I guess it will be a good idea to add such an option.
