### ISSUE TITLE
repeatable_rand is not included in python bindings

### ISSUE THREAD

**Issue by glicerico** [opencog/link-grammar#825]
There's no API to switch the state of the repeatable_rand option for python. 
Is that for a reason, or could it be added?

**Comment by ampli** [comment]
They just be forgotten, I guess because their use is rare.
I added them in PR #826.

BTW, with this PR, future library functions (including options setup) will get defined automatically in the C interface so they will be immediately usable (in their raw library form) independently of the particular language bindings.

**Comment by glicerico** [comment]
Nice, thanks!
