### ISSUE TITLE
Panic Mode

### ISSUE THREAD

**Issue by AmishaTiwari** [opencog/link-grammar#832]
I am using Link-Grammar 5.4 to parse a few long sentences. Using LG on CLI and enabling panic mode by !panic=1, the sentences are getting parsed. 
So, is there any equivalent method in clinkgrammar.py for enabling the same as currently, either it is not able to parse and returning null output or timer (30 sec) is getting expired.

**Comment by linas** [comment]
For python, the below should work, I think. I haven't tested.
```
ParseOptions(max_parse_time=123)
```
it sets the maximum time to 123 seconds, and then gives up if the parse can;t be completed by then

**Comment by linas** [comment]
Panic parses are something else. If a parse cannot be completed in `max_parse_time` then it alters various parameters, and tries again. Unfortunately, this is likely to result in low-quality parses. ... On the other hand, for a long sentence, maybe that is all you need.

Also, for long sentences, the SAT parser is much faster.

 Hmmm. @ampli maybe we should change panic-parse to use SAT (and not change the cost!?)

**Comment by AmishaTiwari** [comment]
@linas I am getting similar results. For the command-line client, I have enabled the panic mode and max_parse_time is 30 secs only. After expiring it enters into the panic mode and is able to find a few linkages passing post-processing stage for some long sentences which are having the relations b/w words on which I am working. 
So, can we do something around ParseOptions: short_length or all_short_connectors so that it could enter into panic mode and return at least a few linkages with whatever disjunct cost. 123 secs is way too much for the sentences which cannot be parsed at all. Even the CLI is not able to parse a few such. So the program will run for weeks to process a complete bunch of files.
I think it's not able to enter the panic mode where it can allow short connectors and islands. If I am changing ParseOptions(short_length=16, all_short_connectors=True), even for short sentences it's returning poor quality parses with disjunct cost very high when compared to CLI results.
So, will the results be fine if I enable all_short_connectors after the timer gets expired?
Or, do I need to consider other options like cost_max < 2.7 to get some parses which CLI is returning.

**Comment by AmishaTiwari** [comment]
These are the values that I have currently set. 
                 verbosity=1,
                 linkage_limit=10000,
                 min_null_count=0,
                 max_null_count=999,
                 islands_ok=False,
                 short_length=16,
                 all_short_connectors=False,
                 display_morphology=False,
                 spell_guess=False,
                 use_sat=False,
                 max_parse_time=123/30,
                 disjunct_cost=2.7,
                 cost_model_type=1
So after the timer gets expired in case of a few long sentences which are True Positives for my case, instead of raising LG_TimerExhausted, what are the options that need to be changed so that the parser could parse them.

**Comment by ampli** [comment]
> Hmmm. @ampli maybe we should change panic-parse to use SAT (and not change the cost!?)

This may be added as an option.
But currently, the usefulness of the SAT parser after a timeout of the classic parser is very limited:
1. It has a potential for giving a parse only if the timeout happened during a parse with null_count==0, as the SAT parser currently cannot parse with null links. But usually the timeout happens while parsing with nulls>0. This is because a classic parse with null_count==0 is relatively fast due to the very effective power-prune that can be done then.
\
I guess that python-LG-bindings users tend to parse with `min_null=0` and `max_null=999`, and regretfully the API doesn't tell you at which null_count the parse timed-out. So the user has to first parse with `max_null=0` in order to usefully invoke the SAT parser afterwards if a timeout happens.
\
From historical reasons, `link-parser` already starts the parsing with `max_null=0`. It is possible to add it an optional SAT parser panic mode (maybe while working on issue #785). But see (2).
2. The classic parser sorts its output to produce the lowest metric parses first. The original SAT parser tried to do that to some extent (the "guiding" module) but I think this got broken on the minisat2 port (I already started to investigate that). So currently the parses are output in a "pseudo random" metric order.
\
To mitigate that, one can gather many parses (e.g. 10000) and sort them (no API for that, even though the library has the needed code). However, currently producing many parses by the SAT parser is very costly (partly because a full pp-pruning is not done in it - I have a fix for that (issue #827)).

**Comment by ampli** [comment]
@AmishaTiwari,
In order to produce parses in a shorter time (but note that they would most probably be lower quality ones), you may try to decrease the following:
- `disjunct_cost` (`cost_max` in `link-parser`)
- `short_length` (`short` in `link-parser`)
- `linkage_limit` (`limit` in `link-parser`)
and also to set
- `all_short_connectors=TRUE` (no UI for it in `link-parser`)

For an example, you can look at the panic-mode parametrs of `link-parser`:= using the yet-undocumented command `!panic_variables` (I quote here only the relevant lines):
``` text
 cost-max     Largest cost to be considered                  4.00
 limit        The maximum linkages processed                  100
 short        Max length of short links                        12
```
In addition, in panic-mode `link-parser` sets `all_short_connectors=TRUE`.

**Comment by AmishaTiwari** [comment]
Thanks for your responses. I have tested it. It is working fine.
Once again Thanks for providing the detailed tech solution.
