### ISSUE TITLE
Failing sql-demo test, because that file is not installed on the system

### ISSUE THREAD

**Issue by LocutusOfBorg** [opencog/link-grammar#858]
this seems a followup of #794

Problem is: we don't want to install demo-sql on the end user system, so the test should silently ignore the case when the file is not installed.
Am I wrong when I say that the file is useless for the end user?
Error:
```
Using <module 'lg_testutils' from '/tmp/autopkgtest.TZ7jNt/build.hPN/src/bindings/python-examples/lg_testutils.py'>
..................................s....................link-grammar: Error: Could not open dictionary "demo-sql/4.0.dict"
E.........................
======================================================================
ERROR: setUpClass (__main__.GSQLDictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests.py", line 737, in setUpClass
    cls.d, cls.po = Dictionary(lang='demo-sql'), ParseOptions()
  File "/tmp/autopkgtest.TZ7jNt/build.hPN/src/bindings/python/linkgrammar.py", line 332, in __init__
    raise LG_DictionaryError('Error: Failed to open dictionary {!r}'.format(lang))
LG_DictionaryError: Error: Failed to open dictionary 'demo-sql'

```

Proposed fix: disable the test, or ignore unavailable file

**Comment by LocutusOfBorg** [comment]
please see failures here:
http://autopkgtest.ubuntu.com/packages/l/link-grammar/disco/amd64

and my "patch":
http://launchpadlibrarian.net/399392386/link-grammar_5.5.1-1_5.5.1-1ubuntu1.diff.gz

**Comment by LocutusOfBorg** [comment]
In case the file is really needed, please tell me, and I'll modify the Debian packaging to start including it.

**Comment by linas** [comment]
Hi @LocutusOfBorg  -- The demo-sql file is not actually needed for they currently running system.  It should not be installed. I assume the test is failing because the build dir is not "near" the source dir, where it would be found.  Your patch looks like a very reasonable work-around. (Perhaps the correct fix would be to copy it into the build dir, and then run the test).

FYI, some day in the future "real soon now", we plan to publish new languages in the sql format. Maybe in half a year. maybe longer. Maybe not officially, for a while.

**Comment by LocutusOfBorg** [comment]
I'm not sure it fixes the issue?

please have a look at:
http://debomatic-amd64.debian.net/distribution#unstable/link-grammar/5.5.1-3/autopkgtest

I applied the patch and ran the testsuite.

The current workflow is:
1) build the package and install it into a subdirectory
2) run this test:
```
cat debian/tests/unit-tests 
#!/bin/sh -x

echo THE CURRENT PATH IS: "${PWD}"
echo "********** START OF FILE LISTING **********"
find .
echo "**********   END OF FILE LISTING **********"
make -C tests check
make -C bindings/python-examples check || (cat bindings/python-examples/test-suite.log && false)
```

you can see in the log the failure
```
ERROR: setUpClass (__main__.GSQLDictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests.py", line 737, in setUpClass
    cls.d, cls.po = Dictionary(lang='demo-sql'), ParseOptions()
  File "/tmp/autopkgtest.DrfCOT/build.rrS/src/bindings/python/linkgrammar.py", line 332, in __init__
    raise LG_DictionaryError('Error: Failed to open dictionary {!r}'.format(lang))
LG_DictionaryError: Error: Failed to open dictionary 'demo-sql'

----------------------------------------------------------------------
Ran 80 tests in 5.793s
```

**Comment by linas** [comment]
Ah, Yes, that is correct, my patch will still fail for this workflow:

1. build the package and install it into a subdirectory
2. run test

Is this how all Debian packages are tested?  

I was assuming:

1. build the package
2. run test in build dir
3. install it into a subdirectory

but I understand why it makes sense to run tests after install, and not before.

**Comment by linas** [comment]
@ampli I'm trying to think of ways for knowing if a test is being run in the build dir, or elsewhere, but cannot think of anything nice, just right now. Ideas?

**Comment by ampli** [comment]
The problem here is another one.

The `make -C bindings/python-examples check` command cannot run from the install location. It can run only from the source directory. And indeed, I see in the logs:
```
FAIL: tests
===========

Running by: /usr/bin/python
Running ./tests.py in: /tmp/autopkgtest.TZ7jNt/build.hPN/src/bindings/python-examples
PYTHONPATH=./../python:../python:../python/.libs
srcdir=.
LINK_GRAMMAR_DATA=./../../data
```

(Also, the install log shows that the demo-sql dict has been installed as needed, but this is not relevant here, as "make check` runs the check in the source directory.)

**The reason of the problem here is:**
```
checking sqlite3.h usability... no
checking sqlite3.h presence... no
checking for sqlite3.h... no
...
	SQLite-backed dictionary:       no
```

Comments:
1. It seems to me that in any case it may not be appropriate to run "make check" ti test the installation, since its purpose is to make a check in the sources directory, and that check may use facilities that are not to be installed.
The official way to test an installation is "make installcheck". (It will also fail in our case die to the missi8ng SQLite support.)
2. If desired, we can have a clear warning at the end of `configure` that SQLite support has not been  included.
3. The library code of dict open error doesn't have an official way to tell the reason of the failure.
However, one can find that by capturing and analyzing the error messages.
In our case, in case of a dict failure error the library code could tell us that **dict.db** has been found but SQLite support has not been compiled in. The demo-sql test can then detect that and not fail if desired.
4. Alternatively to (3), we can mark the demo-sql test with `@unittest.expectedFailure` so it can fail without counting it as a failure, with a message hinted that maybe SQLite support is not compiled int. It is then up to the installer to investigate the real reason.
5. Yet alternatively to (3) and (4), we can somehow (I still don't know how) detect that there is no HAVE_SQLITE and skip the demo-sql test.
6. For distributions that don't want to install demo-sql at all, we can use `@unittest.expectedFailure` that affects `installcheck` (but not `check`).

**Comment by ampli** [comment]
I said:
> The `make -C bindings/python-examples check` command cannot run from the install location. It can run only from the source directory.

To clarify: The `make check` can only run from the build directory, but `tests.py` runs in its directory, which is in the source directory.

**Comment by LocutusOfBorg** [comment]
nice thanks! adding sqlite3 fixed the testsuite! my issue is considered fixed without need of patches or anything else :)
