### ISSUE TITLE
A combination of grammar and a corpus file causes segmentation fault in link-parser

### ISSUE THREAD

**Issue by alexei-gl** [opencog/link-grammar#867]
A combination of a grammar and a corpus causes segmentation fault in link-parser v. 5.5.1
[issue.tar.gz](https://github.com/opencog/link-grammar/files/2701804/issue.tar.gz)

**Comment by alexei-gl** [comment]
```
cat corpus-1.txt | link-parser dict_50C_2018-12-17_0006 -echo=1 -timeout=1
```

**Comment by linas** [comment]
This is easily reproducible. You are blowing out the stack frame.  GDB shows that you've eaten 58236 stack frames, which is more than can fit into the default 8 megabytes of stack.  You can examine the stack limits by typing in `ulimit -a`.  The reason for the blowout is easy to see: line 39 of the dictionary file is 3 megabytes long. 

You can change the stack-size limit, making it larger. When I doubled it: `ulimit -s 16384` then your dictionary loads and everything runs (although I get a lot of timer-expiered's) 

Also: the SQLite dictionary was created explicitly for language learning, so as to avoid the hassle and difficulty of working with the text files. For example: its very hard to read and debug a 3-megabyte-long line of text in a text-file; but its easy to use ordinary SQL commands in SQLite to explore the same.

**Comment by linas** [comment]
By the way, it might also be possible to solve this by converting the recursive call into a flat loop. That might even allow the dictionaries to load faster. Although most dictionaries load pretty quickly, already.

**Comment by ampli** [comment]
> By the way, it might also be possible to solve this by converting the recursive call into a flat loop. That might even allow the dictionaries to load faster. Although most dictionaries load pretty quickly, already.

It seems it will be enough to make it recursive only on the depth of the expression.

**Comment by ampli** [comment]
I made a test in `restricted_expression()`: I modified it to be iterative on the expression RHS and use an unlimited length E_list chain (instead of max. 2 elements). I left the LHS recursive, since its depth is very limited.
I also removed the wrapping of connectors in an AND node. I validated that the parses are the same. (BTW, I didn't validate the `lt` parses because I haven't modified yet the `SYM_AND` operator.)

After this modification, the repository basic/fixes batches run significantly faster (but not the fix-long batch,  which is bounded by the parsing, and is only slightly faster). The language-learning batches  run **significantly** faster.

Also, with this modification `dict_50C_2018-12-17_0006` doesn't take any significant stack (it needs only a few frames). This is true also for the rest of the expression scanning functions, which are all recursive.
The speedup is because the longer E_list chain, which enables to do much of the expression manipulation iteratively. For example, the 3MB expression is basically a long OR E_list chain with max. depth of 1.

Note that if `restricted_expression()`  was only modified to be iterative (without longer E_list chains), stack overflow would still occur in other places (expression copy, marking, deletion, etc.).

Since everything works just faster with unlimited E_list chains, I don't have any idea why they got limited to 2. Also, I don't understand why connectors are wrapped in AND nodes if everything works just fine and faster without that.

Now that the basic idea works, some more optimizations can be done (for simplicity and speedup).

**Comment by ampli** [comment]
> (BTW, I didn't validate the `lt` parses because I haven't modified yet the `SYM_AND` operator.)

I also implemented iterative read of SYM_AND. The relevant expressions from the `lt` dictionary looks totally different when build iteratively since their build order is revered. But I verified them visually and the same linkages result. Similarly to connectors,I removed their wrapping in an AND node, and I think they can still mixed with regular ANDs

The question now is "what next?".
Are there any problems with letting `E_list` chains to be unlimited?
If this seems fine, I will send a PR.

**Comment by linas** [comment]
> Since everything works just faster with unlimited E_list chains, I don't have any idea why they got limited to 2.

About half-a-year ago, I tried to convert the E_list code into "normal" trees, and failed as things kept breaking.  I had a hard time understanding why....

> Also, I don't understand why connectors are wrapped in AND nodes if everything works just fine and faster without that.

Optional connectors are empty-and's. If you can simplify the E_list structure by unwrapping some pointless wraps, that is fine.

OpenCog wraps the LG library, and does import the dictionary by walking the e_list tree.  I'd have to test to make sure that is not broken.  Opencog also noticed the length-2 thing, and .. does some hack .. so changing this might break .. something.  Go ahead and do a pull req, I will have to poke around and test.

**Comment by ampli** [comment]
> About half-a-year ago, I tried to convert the E_list code into "normal" trees, and failed as things kept breaking. I had a hard time understanding why....

Maybe such a conversion can be done incrementally, while validating the result of each step, by an intermediate use of a function that converts from a normal tree to E_list.
But I think that when long E_list chains are used (and only then), the current expression `structure` suddenly looks very logical and efficient way to handle expressions, so such a conversion is not actually a good idea (compared to using long E_list chains).

> Optional connectors are empty-and's.

The implementation of optional connectors seem to me just fine, so I didn't touch it. (But with long E_list chains it should be very efficient to trim extra null expressions inside OR expressions after expression pruning for lighter processing in `build_disjuncts()` and `eliminate_duplicate_disjuncts()` - I didn't try that, but maybe it will yield some speedup for long sentences).


> Opencog also noticed the length-2 thing, and .. does some hack .. so changing this might break

I looked at the relevant code. If needed, it can easily be fixed.
