### ISSUE TITLE
Parsing stops when num_valid_linkages==0 and there was a parse overflow

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#869]
Normally, when no valid linkages are found, the parsing continues with an incremented null_count.
However, at the end of the null_count incrementing loop there is this check:
``` c
    418                 /* If we are here, then no valid linkages were found.
    419                  * If there was a parse overflow, give up now. */
    420                 if (PARSE_NUM_OVERFLOW < total) break;
```
This happens when all the parses have PP violations.
In such a case there are no results.

I think this is not useful, and propose to remove this check. Maybe a warning can be added that suggest to increase the linkage_limit, which often solves the problem - some long sentences have a very low density of valid pp linkages and even linkage_limit>100K is needed.

**Comment by linas** [comment]
Yes, sure. Seems OK to me.

**Comment by ampli** [comment]
It will be included in the next PR (to be sent ASAP).
But I couldn't add the said warning due to a lot of false positives - the `fixes` batch contains a lot of such examples (of all the linkages containing P.P. violations and increasing the length_limit doesn't help).

BTW:
Still  this problem (of very low density of linkages with no P.P. violations) seems to be typical for long sentences. And if a very big linkage_limit is used in a try to solve that, the "Sorted all linkages" consumes MUCH CPU (~1 minute for linkage_limit=1M).
Because the violations tend to repeat in linkages of the same long sentence, I thought to solve that by "caching" the involving links of the P.P. violations, so a fast comparison can be used to see if  a linkage contains a "known" violation (before making an actual postprocessing). For the SAT parser (in which postprocessing is the main bottleneck for long sentences) there is not even a need for such caching, as a constraint can be added to forbid the seen violation in further linkages.

**Comment by linas** [comment]
I once added some checks to post-processing, and found that maybe 1/3 or 1/2 of the PP rules never, ever get triggered.  This is after parsing not only the usual corpus files, but also after parsing some other large files (some books, I think)   I was going to remove the unused rules, but then ... I didn't.   

Given that this affects performance, maybe its time to remove them. 

Also: I have some vague long-term plan to redesign the dict, so that the PP rules are not needed. But this is a lot of work. Also, the language-learning doesn't use PP rules. The hope is that it will never have to.   However, it is possible that maybe some constraints are hard to enforce. This is .. very unclear.  Maybe someday in the distant future, we will discover that there is a need for a certain constraint, and that there is a better, faster way than enforcing it with the ordinary dictionary, and/or that maybe PP is a good way of doing things, after all.  This is all very unclear. 

I don't know what the most common PP rule is. Maybe there is a way to fix the dict, so that the most common PP rules don't trigger....

`struct pp_rule_s `  has `int use_count;        /* Number of times rule has been applied   */` in it and there's `err_msg(lg_Debug, "Used: %d rule: %s\n", set[i].use_count, set[i].msg);`

**Comment by ampli** [comment]
> Given that this affects performance, maybe its time to remove them.

How to proceed in that?

**Comment by linas** [comment]
> How to proceed in that?

Turn on the printing of the PP rule usage summary, and then parse a large variety of text. Wikipedia is easy to get, but wikipedia writing is not typical.  Project gutenberg is easy to get, but everything there is almost 100 years old, and so that's different from modern English. There are some fanfic sites for modern English. I do NOT know of any good newspaper texts.  I don't think its possible to screen-scrape vox.com or medium.com or even 20-year-old new york times news stories,  but that would be ideal.  All this is probably overkill for testing post-processing ... Its late, maybe I better go to bed now :-)

**Comment by ampli** [comment]
After my recent rewrite of pp_prune(), it is very light and redundant rules don't mater much
(I also have another pp_prune() efficiency enhancement in the work that I intend to submit soon).
In addition, I made some changes to the postprocessing that makes it several times faster which is still a WIP.

I will close this issue and will open a new one on removing unused PP rules.
