### ISSUE TITLE
Disjunct left/right sides terminology

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#898]
I'm now making finish touches to the new `power_prune()` which is **very much** faster than the original one. It is based on a novel idea of memory sharing of identical disjunct sides. These leads to several optimizations that improve efficiency.

The question here is about terminology.
I called the left/right sides "disjunct halves". From this several names were derived:
Main strut: `halves_sharing`
Table pointer: `halves_table`
Function to make the sharing: `share_disjunct_halves`
etc.

If you have an idea of a better terminology, I can of course change it.

**Comment by linas** [comment]
How about "quadrants"? Not to mess up your plans, but here's some points to keep in mind:

* The h/d connections have too match as well as +/-
* For some languages, e.g. Lithuanian, russian, turkish (finnish...) the h/d connections are almost the only ones that matter. The +/- connectors could be made optional, not required, unused.  (For backwards compatibility, this is not the case: Russian does not currently use h/d. Lithuanian does use h/d and works around +/- by always adding every connector with both + and - versions, always. Which is sloppy: it doubles the number of connectors, and forces the parser to do direction-matching, when direction-matching is completely un-needed)

* There are examples of this in English, too: The S and SI links are "the same link", but with + and - reversed. They could be replaced by a new link - a "direction-independent S" that only uses h/d for connecting up, and ignores +/-. This is unlikely to happen, for backwards-compatibility, but it could in principle.  Also - the SJ/AJ/MJ/VJ links are also bi-directional, having more-or-less identical + and - versions.They currently use lower-case "l" and "r" in subscripts, because they were invented before the h/d mechanism was invented. The "l" and "r" in subscripts could be (should be?!) replaced by h/d.

* Not too long ago, I was thinking "gee, we could have a third marker, besides h/d, and use it for .... foo ..." and today, I can't remember what "foo" would be. But if  (when?) we get a third marker, then having a "fifth quadrant" might make sense...  (Oh, I think I remember; I was thinking of having a special "x" type, in addition to h/d, for link-crossing-type links. It is an incomplete idea, or maybe a bad idea...) 

The above might not be strong enough reasons to move from a "halves" design to a "quadrants" design. But ... something to think about, maybe.

**Comment by ampli** [comment]
The "halves" idea is agnostic to h/d. For an unknown reason that I still investigate its application in pruning is not agnostic to '@' (multi) (taken care in the code). But it seems that the idea will still work the same if there will be any number of "parts" on the disjuncts (even 3 or 10), as long as the rule that "all the connectors on the disjunct must be satisfied" is preserved. (If this rule is not preserved, some, even  much, code rewrite will be needed anyway.)

A solution to an unknown future numbers of disjunct parts is maybe to use naming that is agnostic to number. Like:
- Disjunct wings (currently left and right wings, maybe in the future also h and d wings).
- Disjunct corners.
- Disjunct arms.
- Disjunct banks.

Or to leave it as halves, so if we have 4 parts we will still have  4 halves "for historical reasons".

BTW, it seems that the same idea should work to increase parsing speed (my next test).

**Comment by linas** [comment]
> agnostic to h/d

Well, I assumed it was "halves" because each "half" is pairable with the other.  So I imagined that adding h/d would split it into fourths.

> wings corners arms banks

How about "jets"?  Its short, unique, non-generic, cannot be confused with other concepts. It also reminds me of "jets" in mathematics, to which there is some kind-of-ish resemblance.

**Comment by linas** [comment]
This probably totally won't make sense to you, but disjuncts are kind-of-like jets: https://en.wikipedia.org/wiki/Jet_(mathematics) in that both tell you how things nearby "connect" to one-another. They hold connectivity information. This is unimportant for the LG code-base, but can provide a handle for the back-ground theory for the "structure of knowledge".

**Comment by ampli** [comment]
Ok, "jets" is fine (I don't like long code statements...).
So for a A+ & B+ & C- & D:
Left jet: C- & D-;
Right jet: A+ & B+.
Main structure: `jet_sharing`;
The tables that holds them: `jet_table[2].`  Etc.

**Comment by ampli** [comment]
> Main structure: jet_sharing;

Or should it be: `jets_sharing`?

**Comment by ampli** [comment]
This is the first commit of the improved `power_prune()` PR:
```
Sentence: Add a field for disjunct jets sharing

"Jet" is the terminology that has been selected for the whole connector
sequence that is in a particular side of a disjunct.
```

**Comment by linas** [comment]
use the singular "jet". just say "A `jet` is a collection of connectors (in a disjunct) all pointing in the same direction"

**Comment by ampli** [comment]
Implemented as discussed.
