### ISSUE TITLE
Words Ignored in Result

### ISSUE THREAD

**Issue by sbguthery** [opencog/link-grammar#992]
verbosity set to 0
graphics set to 1
Echoing of input sentence turned on.
limit set to 1
Display of disjuncts used turned on.
The roads were frightfully bad and there was little communication between one part of the country and another.

    +------------------>Wp------------------>+<--------PFb--------+---------SIs---------+            +----------------------Js---------------------+
    |                               +---EA---+-----MVp----+       |        +-----Dmu----+-----Mp-----+     +------------------IDPN-----------------+
    |                               |        |            |       |        |            |            |     |                                       |
LEFT-WALL [the] [roads] [were] frightfully bad.a [and] there.r was.v-d little.i communication.n-u between one [part] [of] [the] [country] [and] another [.]

            LEFT-WALL    2.000  hWp+ RW+
          frightfully    0.000  EA+
                bad.a    1.100  EA- dWp- @MV+ dPFb+
              there.r    0.000  MVp-
              was.v-d    2.000  PFb- SIs+
             little.i    0.000  Dmu+
    communication.n-u    0.000  Dmu- SIs- @M+
              between    0.400  Mp- J+
                  one    0.000  IDPN+
              another    0.000  IDPN- Js-
           RIGHT-WALL    0.000  RW-

**Comment by ampli** [comment]
The `limit` (number of extracted linkages) is too low...
In order to get meaningful results you need to set a high-enough `limit`, say 1000, due to these reasons:
1. English sentences may have "Post Process violations" (as defined in `4.0.knowledge`), which may invalidate a large percentage of the linkages. If no valid linkage remains, a parsing with a higher number of null-words (ignored words) is tried.
2. Internally, the parser extracts linkages in a random and meaningless  order, and then sorts them according to their "metrics" (the ones that are displayed in the "Found x linkages..." message). So the chance to get meaningful results depend on a "high enough" limit. If you request less linkages than the found ones, the ones to be extracted are a sample which is randomly selected.

For very long English sentences, even a `limit` of 50K or more may be needed. (This can most probably get improved by a large factor by a better post-process algo, but it is towards the end of my TODO list.)

In your case, the "Found" message is:
` Found 330538 linkages (1 of 1 random linkages had no P.P. violations) at null count 7`
It means that when ignoring 0 words, 1 word and so on (until 6 in that case) the randomly sampled single linkage was an invalid one, and it happened to be valid only on the try with 7 null words).

With `limit=1000` (the default of `link-parser`, all other options are default too) the message for this sentence is:
`Found 1360 linkages (219 of 1000 random linkages had no P.P. violations)`
It means that only about one out of 5 possible linkages (when no word is ignored) is valid here, so you have a low chance to get a valid linkage with a single random selection.

**Comment by linas** [comment]
The default settings give me the below, which appears to be exactly correct:
```
linkparser> The roads were frightfully bad and there was little communication between one part of the country and another.
Found 1360 linkages (219 of 1000 random linkages had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 2.75 LEN=34)

    +------------------------------------------------------------------------Xp------------------------------------------
    +-----------------------Xx----------------------+
    +--------->WV-------->+                         |              +----------------MVp---------------+
    +---->Wd-----+        +--------Paf-------+      +----->WV----->+---------Out---------+            +-----Js----+    +-
    |      +-Dmc-+---Spx--+         +---EA---+      +--Wdc-+<-SFut-+        +------A-----+-----Mp-----+     +--Ds-+-Mf-+
    |      |     |        |         |        |      |      |       |        |            |            |     |     |    |
LEFT-WALL the roads.n were.v-d frightfully bad.a and.ij there.r was.v-d little.a communication.n-u between one part.n of


------------------------------+
                              |
                              |
-------Ju--------+            |
 +-Ds**c+--SJls--+--SJrs-+    |
 |      |        |       |    |
the country.n and.j-n another .

```
